### ISSUE TITLE
WSGI middleware for webhook signature validation

### ISSUE THREAD

**Issue by skimbrel** [twilio/twilio-python#159]

**Comment by zwhite** [comment]
I just wrote some wsgi middleware that validates that a request comes from twilio. It still needs to go through our security review and open sourcing process, but I should be able to contribute it. What would be the best place to put such a thing? It's just one class, 25 lines or so total.

**Comment by skimbrel** [comment]
Probably the `util` module, which looks like it's starting to get a bit long. If you're up for pulling it apart into a package with say a `request_validator.py` and a `capability.py` module, that'd be awesome. If not, feel free to send a PR with the middleware stuck in `util.py` and I'll tease it apart myself when I've got a moment.

**Comment by zwhite** [comment]
I'll see what I can put together. What would go into the `capability.py` module?

**Comment by skimbrel** [comment]
The existing `TwilioCapability` class and its dependency `ScopeURI`. We'd want the new `util/__init__.py` to import all of the moved names so they'd still be available as `from util import x` for backwards-compatibility. Thanks!

**Comment by zwhite** [comment]
I haven't tested this at all yet and I need to write tests for the middleware, but here's [a first stab at teasing it apart and adding my middleware](https://github.com/zwhite/twilio-python/commit/828a168aaf245b52544f5a99f3115e38d8a286b7). (Sorry about the weird indent, we have strange local customs I'll have to fix before generating a pull request.)

Am I on the right track here?

**Comment by tstirrat15** [comment]
If not this, what about a function that takes signature header, body, and the signature key and spits out a verification boolean? The logic around webhook verification is fiddly enough that it'd be nice to have an abstraction around it.

**Comment by childish-sambino** [comment]
@tstirrat15 Does the [RequestValidator](https://github.com/twilio/twilio-python/blob/master/twilio/request_validator.py) suite your needs?

**Comment by tstirrat15** [comment]
It totally does. I think I was thinking of another library when I stumbled over this issue... I appreciate your response, though.
