### ISSUE TITLE
Transfer Number from sub-account to master account

### ISSUE THREAD

**Issue by dotmat** [twilio/twilio-python#164]
The code for transferring sub account to master account is not correct and is missing the sub account point, example 

client = TwilioRestClient("AC...MASTERSID","AUTHKEY") 
number = client.phone_numbers.get("PN...").update(account_sid="AC... SID receiving")

In Java it has: 

IncomingPhoneNumber number = client.getAccount("AC...Subaccount..FROM).getIncomingPhoneNumber("PN...");
client.getaccount("SUBACCOUNTSID").get...

**Comment by alexcchan** [comment]
There's a workaround using the internal `PhoneNumbers` class directly:

```
from twilio.rest import TwilioRestClient
from twilio.rest.resources import PhoneNumbers

client = TwilioRestClient(account_sid, auth_token)
phone_numbers = PhoneNumbers('https://api.twilio.com/2010-04-01/Accounts/%s' % subaccount_sid, client.auth)
phone_number = phone_numbers.get(phone_number_sid)
phone_number.update(account_sid=new_account_sid)
```
