### ISSUE TITLE
Python 3: RequestValidator failing due to bytes/string comparison

### ISSUE THREAD

**Issue by seedifferently** [twilio/twilio-python#165]
I'm using this package with Python 3.4 and the `RequestValidator.validate()` method is failing (even though I have verified manually that it should succeed).

I think this is due to the fact that the `compute_signature` method returns bytes, but is then passed to the `secure_compare` method without being converted to a string.

**Comment by mrhwick** [comment]
I have recently upgraded my codebase to run on Python 3. It appears that we are running into this issue on production. I will continue investigating, but any additional information would be helpful.

**Comment by mrhwick** [comment]
To follow up. It seems that this issue has been fixed as of version 3.6.9 (see link here: https://github.com/twilio/twilio-python/blob/3.6.9/twilio/util.py)
