### ISSUE TITLE
Request timeout is never evaluated when using client.messages.create()

### ISSUE THREAD

**Issue by enfyra** [twilio/twilio-python#169]
When specifying the timeout= keyword to the create() method, the timeout value will never make it to the request.

All keywords are converted from lowercase to camel case, so "timeout" becomes "Timeout". However, in rest/resources/base.py, line 178, a comparison is made to check the timeout value.

if 'timeout' not in kwargs and self.timeout is not UNSET_TIMEOUT:

This is checking for 'timeout' instead of 'Timeout'. A possible fix would be to force a lowercase check:

if 'timeout' not in [k.lower() for k in kwargs] and self.timeout is not UNSET_TIMEOUT:

**Comment by carlosdp** [comment]
Looks like this was resolved in abdc9ad0
