### ISSUE TITLE
twilio.TwilioRestException - Docs bug, or import problem?

### ISSUE THREAD

**Issue by foxx** [twilio/twilio-python#183]
The [docs](https://twilio-python.readthedocs.org/en/latest/api/rest/) say that `TwilioRestException` can be accessed from `twilio.TwilioRestException`, but this is not the case.

You instead need to use `twilio.rest.exceptions.TwilioRestException`.

Is this a documentation bug, or should `twilio.TwilioRestException` actually work?

**Comment by Altrum** [comment]
can we update the docs located here? https://twilio-python.readthedocs.io/en/latest/api/rest/
I would do it but I can't seem to find the file associated with it.

**Comment by atbaker** [comment]
Hey @Altrum - thanks for letting us know. The docs on Read the Docs were definitely out of date, I just pulled them down.

The best place for docs and sample code on using this library live on www.twilio.com/docs. We have lots of automation and testing in place on those docs to make sure they're always up to date.

Let me know if you can't find what you're looking for there and I can try to help.

**Comment by mahimakaushik-oss** [comment]
TwilioRestException: Unable to create record: Permission to send an SMS has not been enabled for the region indicated by the 'To' number:______________

i am using twilio first time for sms and its showing this error .can anyone help me to solve this problem.

**Comment by childish-sambino** [comment]
@mahimakaushik-oss Please open a new issue.
