### ISSUE TITLE
TwilioRestException always prepends the error code in the msg attribute

### ISSUE THREAD

**Issue by morrissimo** [twilio/twilio-python#202]
...which prevents custom exception handling from making fine-grained formatting decisions for downstream user display - like, "I don't want to display Twilio error codes to my end users, but I would like to use the Twilio exception message text".

**Comment by morrissimo** [comment]
Specifically, I think [this line](https://github.com/twilio/twilio-python/blob/master/twilio/rest/resources/base.py#L154):
```python
message = "%s: %s" % (code, error["message"])
```
...should be:
```python
message = error["message"]
```

**Comment by skimbrel** [comment]
Seems reasonable, considering we already make the code accessible as a separate attribute. Want to write up a quick PR?
