### ISSUE TITLE
twilio requires six > v1.4.1, pytz > 2013.7

### ISSUE THREAD

**Issue by bmccormack** [twilio/twilio-python#208]
I was trying to use the Twilio python library, installed via `sudo pip install twilio`. It installed fine, but when I tried to run my code, I got the following error:

```
$ python play_with_twilio.py
Traceback (most recent call last):
  File "play_with_twilio.py", line 1, in <module>
    from twilio.rest import TwilioRestClient
  File "/Library/Python/2.7/site-packages/twilio/__init__.py", line 4, in <module>
    from six import u
ImportError: No module named six
```

Looking at `pip freeze`, I saw that I had `six==1.4.1`.

Running `sudo pip install six --upgrade` brought me up to version 1.9.0.

I had to do the same thing with `pytz` to get to 2014.10 from 2013.7.

This got me past the import errors.

**Comment by ueg1990** [comment]
Did you do  sudo pip install twilio inside a virtual environment or outside? If outside, then maybe you had six and pytz installed earlier in your local environment and needed to be upgraded to satisfy the requirements of twilio-python.

**Comment by bmccormack** [comment]
@ueg1990 It was outside a virtual environment. I did in fact have six and pytz installed earlier and needed to upgrade. I guess what I'm wondering is if there's a way to specific a minimum required version in the twilio PyPi package so that my system would automatically know to grab an updated version of six and pytz.

**Comment by ueg1990** [comment]
The best way would be to setup a virtual environment, and do your installation there. That way you will not have to worry about required versions and stuff. It is considered good practice now to do your python projects in isolated virtual environments. 

I am assuming the alternate option you can try is:

sudo pip install twilio --upgrade

Maybe that will automatically take care of the updated versions

**Comment by carlosdp** [comment]
Yea, @ueg1990 is spot on, it's best to use a virtualenv!

**Comment by hiresh** [comment]
installed six and pytz but still shows the same error..kindly inform about the directory structure in which all the modules are to be installed, I am using python2.7 and pythonwin as IDE on a 32bit windows machine.
