### ISSUE TITLE
New line feature no longer working as of today

### ISSUE THREAD

**Issue by bhamodi** [twilio/twilio-python#209]
Hey guys,
I've been using Twilio every day for a single daily text message and just starting today I noticed that the new lines in my body text did not render.
I haven't changed the code on my end, so I'm trying to figure out what went wrong.
I've been using `\n` so far, and after some research, some people claimed that I should be using `%0a` but that didn't work either. In fact using `%0a` didn't escape the new line it just outputted `%0a` as part of the text.
Additional info: I've been using Twilio version 3.7.2 all this time. The same issues mentioned above were present when I updated to Twilio 4.0.0.
Here is a snippet of my code:
```python
twilio_client = TwilioRestClient(twilio_account_sid, twilio_auth_token)
twilio_client.messages.create(body="Prev:          $ {0:.2f}".format(prevBalance) + "\nTotal:         $ " + totalBalance + "\nChange: " + totalDifference, to=personal_number, from_=twilio_number)
```
Hopefully we can resolve this issue quickly. Thanks!

**Comment by skimbrel** [comment]
Hey Baraa,

Can you open a support ticket with help@twilio.com? They're better equipped to see whether this is an issue with one of our carriers affecting SMS delivery.

Cheers,
Sam

**Comment by bhamodi** [comment]
Thanks @skimbrel - will do.

**Comment by enwar3** [comment]
@bhamodi It'd be great if you could follow up with what you hear - I have the exact same issue, starting at the same time a couple days ago.

**Comment by skimbrel** [comment]
This is indeed due to a problem with one of our SMS carriers; please write in to help@twilio.com for updates or follow status.twilio.com.

**Comment by bhamodi** [comment]
@enwar3 - Twilio is working on it. This is the response I got from Twilio support:
"We received an update from our provider. They have a fix for this issue, but will need to make a production change which will need to be tested and deployed. This could take a few days."

**Comment by enwar3** [comment]
Thanks guys!  Looking at status.twilio.com, this is the status as of 3 hours ago:

We are continuing to work toward a resolution on new lines not being preserved on outgoing SMS with AT&T, T-Mobile, Verizon & Sprint. We have confirmed the issue with our carrier partners and are working with them on an ETA for when the issue will be resolved.
