### ISSUE TITLE
Multiring with Twilio/Python

### ISSUE THREAD

**Issue by ThomasErento** [twilio/twilio-python#210]
Hi !

Is it possible to use twilio python to mutli ring several phone number from a unique number ? (All sellers, all supports and so on...)
If so, how can I do that ?

Thanks a lot

**Comment by ThomasErento** [comment]
I want to generate somehting like that : 

#<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial>
        <Number>415-123-4567</Number>
        <Number>415-123-4568</Number>
        <Number>415-123-4569</Number>
    </Dial>
</Response>

**Comment by skimbrel** [comment]
Yep, just invoke `number()` on the Dial object multiple times:

```
with twiml.Response() as r:
    with r.dial() as d:
        d.number("+14151234567")
        d.number("+14151234568")
        d.number("+14151234569")
    return r.toxml()
```

Also, I'd strongly encourage you to output your numbers in E.164 format (i.e. `+14158675309` like I did above) both in TwiML and when you call the REST API. This removes any ambiguity in number parsing and will future-proof your code against international numbers if you ever need to handle those. For more reading: https://www.twilio.com/help/faq/phone-numbers/how-do-i-format-phone-numbers-to-work-internationally

**Comment by ThomasErento** [comment]
Great, thanks a lot ! I actually do use this format (+49*** here in germany)
