### ISSUE TITLE
client.sms.messages.create breaks up message if there are special characters

### ISSUE THREAD

**Issue by scarrico** [twilio/twilio-python#212]
If I call:
message = client.sms.messages.create(to=phone, from_=fphone,body=msg) using python on ubuntu

and the msg variable has a special degree symbol entered in excel on a PC and exported in csv it breaks up the message into 3 separate messages.

**Comment by philnash** [comment]
Hey @scarrico,

`client.sms.messages` is using a deprecated endpoint on the API. If you change that up to use `client.messages` instead you will find your problems go away.

**Comment by scarrico** [comment]
Thanks. All fixed now.

**Comment by philnash** [comment]
Great to hear! Let us know if there's anything more we can help with!
