### ISSUE TITLE
test_client.RestClientTest is useful for testing; why not ship it in the module proper?

### ISSUE THREAD

**Issue by jMyles** [twilio/twilio-python#214]
If you pip install this package, you get the inner module (twilio-python.twilio).  

This means that you can't import twilio-python.tests.test_client.RestClientTest, which is a reasonable thing to want to do in order to make use of its mock logic.

Can we move test_client to from twilio-python.tests to twilio.rest?

**Comment by skimbrel** [comment]
Sure, that sounds totally reasonable. If you've got a second to shuffle it around and put up a PR that'd be awesome; otherwise I'll probably be able to get to this early next week.

**Comment by jMyles** [comment]
You know what man, I totally misread the class.  At a cursory glance, I thought it was a mixin with pre-fab'd mocks - I read it as "RestTestClient," not "RestClientTest."  It actually appears that it's just a test case, not a rest client mocking tool.

**Comment by skimbrel** [comment]
Ah, yeah… we do most of the mocking the verbose way. Sorry bout that!
