### ISSUE TITLE
How to search for phone numbers with SMS capabilities

### ISSUE THREAD

**Issue by gregeinfrank** [twilio/twilio-python#215]
Hi, 

I'm using `twilio-python` to search for and purchase new phone numbers. I need phone numbers to have SMS capabilities. How do I search for numbers with a guaranteed given capability? I tried 

```python
client.phone_numbers.search(capabilities={'SMS': True})
```

but that doesn't seem to do anything.

Thanks!

**Comment by skimbrel** [comment]
The capability flags are decomposed into three separate list filters. For this case, pass `sms_enabled=True` to `search()`.

**Comment by gregeinfrank** [comment]
awesome, thanks @skimbrel !

Is this documented anywhere?

**Comment by skimbrel** [comment]
Yep. The REST API documentation on twilio.com is the authority on the API's behavior: https://www.twilio.com/docs/api/rest/available-phone-numbers

**Comment by gregeinfrank** [comment]
Ah I see now, thanks!

**Comment by gcapiel** [comment]
The documentation actually has voice_enabled='true' instead of what you have above.  Also, it doesn't document sms_enabled, you just have to guess that works.
