### ISSUE TITLE
Exception when trying to get a transcription object from a call object

### ISSUE THREAD

**Issue by kazuar** [twilio/twilio-python#222]
Hello,

Thank you for this package it really helped me retrieve required data from the API.

I think there's a small issue with getting a transcription from a call object.
For example, this code:
client = TwilioRestClient(<ACCOUNT_SID>, <AUTH_TOKEN>)
call = client.calls.get(sid = sid)
recording = call.recordings.list()[0]
recording.transcriptions.list()

will result with the following error:
"The requested resource ... was not found"
(I even tried running recording.load_subresources() which didn't help).

However, if I retrieve the recording object again using the sid, everything will work.
For example, this code will work:
client = TwilioRestClient(<ACCOUNT_SID>, <AUTH_TOKEN>)
call = client.calls.get(sid = sid)
recording = call.recordings.list()[0]
recording = client.recordings.get(sid = recording.sid)
recording.transcriptions.list()

Please let me know if I'm missing anything or if you need more information regarding this.

Thanks!

**Comment by carlosdp** [comment]
Thanks for letting us know, this will be fixed in a release within the next week or so, I will close this issue when that happens.

In the meantime, that is a good workaround.

**Comment by carlosdp** [comment]
If you upgrade to version `6.0.0rc2`, this bug has been eliminated. [Read the upgrade guide
