### ISSUE TITLE
Participants don't have an SID

### ISSUE THREAD

**Issue by richardcornish** [twilio/twilio-python#223]
The [REST documentation](https://www.twilio.com/docs/api/rest/participant) correctly states that participant objects don't have an SID attribute.

However, the examples in the [Python documentation](https://twilio-python.readthedocs.org/en/latest/usage/conferences.html#listing-participants), the [Ruby documentation](http://twilio-ruby.readthedocs.org/en/latest/usage/conferences.html#listing-participants), the [SalesForce documentation](http://twilio-salesforce.readthedocs.org/en/latest/usage/conferences.html#listing-participants), and the examples in the API explorer ([View participant for conference](https://www.twilio.com/user/account/developer-tools/api-explorer/conference-participant) and [View participant list for conference](https://www.twilio.com/user/account/developer-tools/api-explorer/conference-participant-list)) all erroneously state that each participant has an SID.

The Python docs:

```
for participant in conference.participants.list():
    print participant.sid
```

Traceback:

```
>>> participants = conference.participants.list():
>>> participants[0].sid
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Participant' object has no attribute 'sid'
```

Being that there is no unique identifier for participants (they are essentially a many-to-many through table for accounts with extra metadata for that particular conference), maybe it's better to just display the native `participant` object.

**Comment by carlosdp** [comment]
Hey @richardcornish, you're right, the library documentation for those you mentioned are incorrect (and the snippets in the explorer as well), thanks for letting us know!

Participants don't have their own sid, but they do have a `CallSid`, because Participants are actually a mapping between a Conference and the individual Calls which make up the participants in the conference call.

I'll open a ticket on this and close the issue when this is fixed.

**Comment by philnash** [comment]
Hey @carlosdp, did this get updated in the docs?

**Comment by efossier** [comment]
Our new 6.x library has been rebuilt from the ground up and therefore documentation has changed, please upgrade and let us know if the problem persists.
