### ISSUE TITLE
Encoding '&' issue in message body

### ISSUE THREAD

**Issue by jpsimos** [twilio/twilio-python#228]
When the ampersand is within a message body, the library appends a '@' to the end of the message. This may not be the only case when the '@' is appended, perhaps this is an encoding issue with the libraries.

**Comment by carlosdp** [comment]
Hi, in order to debug this issue, we're going to need more details about what exactly the error your getting is exactly so we can attempt to replicate it. In the meantime, I'll close this issue since it's been a few months.
