### ISSUE TITLE
Twilio cannot be installed because my country is not on the list of countries supported by Twilio. I need Twilio for learning purposes at Udacity. Is there any other way to learn Twilio/Python work?

### ISSUE THREAD

**Issue by playwriter** [twilio/twilio-python#230]

**Comment by carlosdp** [comment]
Hey @playwriter, you do not have to be in a supported country to use Twilio, that just means you can only buy numbers in those countries (or call those countries, depends on the level we support it). If you need more help on this, please contact our Support and they will get back to you right away. https://www.twilio.com/help/contact .

These issues are really only for issues directly related to the python library itself. Thanks!
