### ISSUE TITLE
Total resource count should be available for ListResource instances

### ISSUE THREAD

**Issue by morrissimo** [twilio/twilio-python#236]
I'd like to be able to do something like this:
```python
>>> import datetime
>>> from twilio.rest import TwilioRestClient
>>> client = TwilioRestClient(account_sid='', auth_token='')
>>> before = datetime.datetime.utcnow() - datetime.timedelta(days=30)
>>> recordings = client.recordings.list(before=before)
>>> recordings.total_count
4606622
```

Oddly enough, this count of the total resources returned is already available in the details of the response itself:
```python
>>> import json
>>> from twilio.rest.base import make_twilio_request, transform_params
>>> resp = make_twilio_request('GET', client.recordings.uri + '.json',
...        params=transform_params({'before': before}), auth=client.auth)
>>> data = json.loads(resp.content)
>>> data.get('total')
4606622
```

**Comment by morrissimo** [comment]
It's fairly edge-case: monitoring mass-cleanup of old recording resources :) And I wouldn't have even filed an issue if I hadn't discovered the ```total``` value already present in the (internal) response data.

**Comment by carlosdp** [comment]
Gotchya, well the `total` field is actually in the process of being deprecated (it's already gone for all new accounts), so that's not going to be a reliable way to handle that in the future.

Instead, you should use the UsageRecords api: https://www.twilio.com/docs/api/rest/usage-records .

Let me know if you need more guidance!

**Comment by carlosdp** [comment]
You can also use the Monitor API to listen for `recording.delete` events to make sure you are deleting recordings consistently: https://www.twilio.com/docs/api/monitor/events

**Comment by morrissimo** [comment]
> Gotchya, well the total field is actually in the process of being deprecated (it's already gone for all new accounts), so that's not going to be a reliable way to handle that in the future.

Roger that - will look at the ```usage-records``` endpoint(s). Thanks!
