### ISSUE TITLE
ImportError: No module named rest.ip_messaging

### ISSUE THREAD

**Issue by MichaelGradek** [twilio/twilio-python#249]
Hi,

The first example I try to copy+paste from [your docs](https://www.twilio.com/docs/api/ip-messaging/rest/channels) does not seem to work. Looks like the imports are not working.

``` python
from twilio.rest.ip_messaging import TwilioIpMessagingClient
```

```
ImportError: No module named rest.ip_messaging
```

**Comment by carlosdp** [comment]
Are you sure you are on the latest version of the library?

**Comment by yfaber** [comment]
i'm having a similar problem. Running the most update twilio version as well.

**Comment by carlosdp** [comment]
@yfaber what extact version are you on?

**Comment by carlosdp** [comment]
@yfaber which exact version are you using?

**Comment by mickstevens** [comment]
Possibly related, I couldn't find any reference in the docs (http://twilio-python.readthedocs.org/en/release-6x/) as to how to deal with access tokens for IPM?

The previous "from twilio.access_token import AccessToken, IpMessagingGrant" now returns:

ImportError: No module named access_token

Mac OS X 10.11 Beta (15A279b)
Python 2.7.10
pip 8.0.2
twilio (6.0.0rc2)

Apols in advance if numpty question.

Rgds, Mick

**Comment by carlosdp** [comment]
@mickstevens oh, are you using the 6.x release candidate? That library has different import directives. Check out https://github.com/twilio/twilio-python/wiki/Python-Version-6.x-Upgrade-Guide .

**Comment by carlosdp** [comment]
@mickstevens sorry, that's our bad, a release candidate was mis-versioned and made the default download. You should download a 5.x version, unless you want to upgrade to the pre-release.

**Comment by carlosdp** [comment]
@MichaelGradek @yfaber ^ that might be your issue as well

**Comment by mickstevens** [comment]
I'm awarding myself a "No-Prize"! So basically IPM not supported yet in 6.0.0rc2? No biggie, like you say, I can rollback, was just keen to checkout the new secret sauce!

**Comment by carlosdp** [comment]
@mickstevens  it is, it's just all the subdomains in the new version are under twilio.rest.Client, so there isn't 1 client per subdomain now.

It's us that get no-prize, the RC shouldn't have been the default version =P

**Comment by mickstevens** [comment]
Ok, so what's the solution to my problem statement/error msg above. Again I can't see any reference to Access Tokens in the upgrade guide or v6 docs?

**Comment by carlosdp** [comment]
@mickstevens you know what, I don't think access tokens have been merged into the RC yet. I'll get that out for RC4 (RC3 is a small release today that makes auth more efficient). thanks!

**Comment by mickstevens** [comment]
This is getting a bit frustrating. Please actually read my comments before replying.

I repeat: 

"So what's the solution to my problem statement/error msg above."

Hint: don't refer people to documentation before checking yourself that said documentation does actually contain the answer (or even exists).

Access Tokens clearly don't work "just as before" or I presumably wouldn't be getting the err msg. My code is based on https://www.twilio.com/docs/api/rest/access-tokens & https://www.twilio.com/docs/api/ip-messaging/guides/identity#create-token (pretty much the only documentation I can find)

**Comment by carlosdp** [comment]
@mickstevens I apologize, when I originally directed you to the docs, I thought access tokens were in the RC and worked just as before. I've since noted that they are not in the 6.x.rc release candidate at the moment, that's a pre-release that still has a few kinks in it. If you need to use access tokens right now, you need to downgrade to a 5.x version or wait for the rc3 release.

So again, the solution is either downgrade to 5.x and use it exactly as you were trying to use it or wait for 6.0.rc3 and use it exactly as you were trying to use it.

**Comment by mickstevens** [comment]
So (as I said 3 hrs ago) IPM, of which Access Tokens is an instrinsic part, is NOT currently supported in v6!

I implore you, for future reference, when responding to a customer "get it right first time, every time".

Looking fwd to your talk at Signal on this, expect some mild heckling (kidding, we'll laugh about it over a beer!).

Signing off & rolling back to v5... :'-(

**Comment by philnash** [comment]
Hey @mickstevens, @MichaelGradek,

Sorry this has been quiet for such a long time. I've just taken a look through the repo and it looks like IP Messaging access tokens were added in v6 rc3 here: https://github.com/twilio/twilio-python/commit/3c474e5584c7c3ebefc228666fb3e286571d0899.

Have you tried using the latest release candidate with this? Can we close this issue?

Thanks!

**Comment by jingming** [comment]
hey @mickstevens @MichaelGradek! 

Twilio Programmable Chat has been added in the latest release of the library!
