### ISSUE TITLE
API Keys not working as expected

### ISSUE THREAD

**Issue by imthepitts** [twilio/twilio-python#259]
**Version: 5.3.0**
**API Subdomain (api/taskrouter/ip_messaging): api**

### Code Snippet
```python
key_sid = 'SKxxxxxxxxxxxxxxx'
key_secret = 'secret stuff'
try:
client = twilio.rest.TwilioRestClient(key_sid, key_secret)
client = client.accounts.get(account_sid)
return client

except twilio.TwilioRestException as e:
return e
```

### Exception / Log
```
�[31m�[49mHTTP Error�[0m �[37m�[49mYour request was:�[0m
�[36m�[49mGET
https://api.twilio.com/2010-04-01/Accounts/AC5f228d24e063ce8009032ef59ebb29b8.json�[0m
�[37m�[49mTwilio returned the following information:�[0m
�[34m�[49mAuthenticate�[0m
�[37m�[49mMore information may be available here:�[0m
�[34m�[49mhttps://www.twilio.com/docs/errors/20003�[0m
```

### Steps to Reproduce
1. Create an API Key in Account Portal
2. Use the key and secret to instantiate `TwilioRestClient`
3. Attempt to get the account
4. Receive 20003 error

**Comment by carlosdp** [comment]
@imthepitts this is expected behavior, you can't use a Key Secret to get an Account.

**Comment by bhyman** [comment]
This worked prior to 1/20/16. And I've analogous PHP code that still works -- is that going to be considered undesirable behavior, treated as a bug, and fixed?

My real question is, how can API keys be used to get an Account / send SMSs?

**Comment by carlosdp** [comment]
@bhyman well there's no way to get an Account via key secrets period, it's simply not allowed by the API. As for other resources, we're adding that to Python in the next minor release.

**Comment by carlosdp** [comment]
@bhyman you can use API key auth now in twilio-python 5.4.0 like this:

```python
client = TwilioRestClient('SKjjhf88gf9jfjf8', 'mmdf792=e8fkd', request_account='ACxxxxxx')
client.calls.list()
```

**Comment by bhyman** [comment]
@carlosdp, thanks, I'll give that a shot. The code I had, which I'd received from someone in Twilio support and which worked for a while, must have relied on something undocumented/internal that was subsequently removed.
