### ISSUE TITLE
6.0rc3 IP messaging broken: Access token JWT encoding incompatibility

### ISSUE THREAD

**Issue by liebald** [twilio/twilio-python#260]
The code in twilio/access_token.py passes a headers kwarg into the jwt.encode function. However, the commit that added this kwarg (https://github.com/twilio/twilio-python/commit/e0c29fac53bcccb39e3770a9e32b3785b017ae3d) wasn't included in the commits leading up to this branch. Hence, calling token.to_jwt() reliably (and unsurprisingly) leads to an error.

More specifically AccessToken.to_jwt() calls
```python
return jwt.encode(payload, self.secret, headers=headers, algorithm=algorithm)
```
but encode (defined in twilio/jwt/__init__.py) has the following signature in the release candidate:
```python
def encode(payload, key, algorithm='HS256'):
```
Hence passing a headers keyword argument leads to an error.

**Version:**
6.0rc3
**API Subdomain (api/taskrouter/ip_messaging):**
ip_messaging

### Code Snippet
```python
# from demo examples
  # Create access token with credentials
  token = AccessToken(account_sid, api_key, api_secret, identity)
  #....
  # Return token info as JSON
  return jsonify(identity=identity, token=token.to_jwt())
```

### Exception / Log
```
  File "/path/to/views.py", line 76, in twilio_ipm_token
    return jsonify(identity=identity, token=token.to_jwt())
  File "/path/to/venv/lib/python2.7/site-packages/twilio/access_token.py", line 91, in to_jwt
    algorithm=algorithm)
TypeError: encode() got an unexpected keyword argument 'headers'
```

### Steps to Reproduce
1. pip install git+https://github.com/twilio/twilio-python@release-6x
2. Download and install demo app at https://github.com/TwilioDevEd/ipm-quickstart-python to work
3. Load index handler

**Comment by philnash** [comment]
Hey @liebald,

Thanks for reporting this and sorry there hasn't been a response. Looks like this was updated in this commit: https://github.com/twilio/twilio-python/commit/5e3ea2f231e33f060b0cbf0de384c9e1fdbe191e and [seems like the method signature is correct now](https://github.com/twilio/twilio-python/blob/089dcde6470bad052b3174988259c07d9a00e2e2/twilio/jwt/__init__.py#L44), though may not be in a released version just yet. Can you check this again?
