### ISSUE TITLE
Phone lookup cannot handle spaces.

### ISSUE THREAD

**Issue by christophebiocca** [twilio/twilio-python#266]
**Version:** 5.4.0
**API Subdomain (api/taskrouter/ip_messaging):** Rest Lookups

### Code Snippet
```python
from twilio.rest.lookups import TwilioLookupsClient
client = TwilioLookupsClient(account=ACCOUNT_SID, token=AUTH_TOKEN)
client.phone_numbers.get('(555) 555-5555')
```

### Exception / Log
```
/python3.5/site-packages/twilio/rest/resources/lookups/phone_numbers.py in get(self, number, include_carrier_info, country_code)
     65         params = transform_params(params)
     66         uri = "%s/%s" % (self.uri, number)
---> 67         _, item = self.request("GET", uri, params=params)
     68 
     69         return self.load_instance(item)

/python3.5/site-packages/twilio/rest/resources/base.py in request(self, method, uri, **kwargs)
    198 
    199         kwargs['use_json_extension'] = self.use_json_extension
--> 200         resp = make_twilio_request(method, uri, auth=self.auth, **kwargs)
    201 
    202         logger.debug(resp.content)

/python3.5/site-packages/twilio/rest/resources/base.py in make_twilio_request(method, uri, **kwargs)
    162 
    163         raise TwilioRestException(status=resp.status_code, method=method,
--> 164                                   uri=resp.url, msg=message, code=code)
    165 
    166     return resp

TwilioRestException: 
HTTP Error Your request was:

GET https://lookups.twilio.com/v1/PhoneNumbers/(555) 555-5555?

Twilio returned the following information:

```

There is no actual information returned.

### Steps to Reproduce

1. Try to validate any number with a space in it
2. Weep

### Culprit Code

https://github.com/twilio/twilio-python/blob/master/twilio/rest/resources/lookups/phone_numbers.py#L66

Pretty sure it needs to escape the number before sending it, but since I don't have access to the server source code I do not know what escaping conventions it expects.

Testing the [demo](https://www.twilio.com/lookup) works fine so the issue is not likely to be with the server endpoint.

**Comment by ihumanable** [comment]
The encoding requirement for national formatted numbers is documented here https://www.twilio.com/docs/api/lookups#lookup-with-national-formatted-number

**Comment by christophebiocca** [comment]
Well that's confusing. Most of the other language bindings don't require this (because they escape it themselves).

I guess that can't be fixed in a backwards compatible way. We'll just wrap the API.
