### ISSUE TITLE
KeyError in twilio.rest.TwilioRestClient.usage.records#count

### ISSUE THREAD

**Issue by ojengwa** [twilio/twilio-python#268]
Ran into this error when I tried query the client usage from the Python SDK.

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```python
# paste code here
```

### Exception / Log
```

~/.virtualenvs/.../lib/python2.7/site-packages/twilio/rest/resources/base.pyc in count(self)
    389         # as possible
    390         resp, page = self.request("GET", self.uri)
--> 391         return page["total"]
    392 
    393     def iter(self, **kwargs):

KeyError: 'total'


```

**Comment by philnash** [comment]
Hey @ojengwa,

Sorry for the slow response. This is expected now as the API no longer returns a total. You can see the [pagination options that the API returns here in the docs](https://www.twilio.com/docs/api/rest/response#response-formats-list-paging-information).

The [deprecation and sunsetting notice was posted last year on the engineering blog](https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging).
