### ISSUE TITLE
Provide "hello monkey" demo for Twilio NextGen

### ISSUE THREAD

**Issue by OliPicard** [twilio/twilio-python#269]
I noticed that in the new documentation there is no mention of new types of tutorial based applications, the ones provided simply fire a request to a pre-programmed endpoint but it would be good to see how you would create Hello Monkey in the NextGen python lib.

The original "hello monkey" application can be found at https://www.twilio.com/docs/quickstart/python/sms/hello-monkey

**Comment by philnash** [comment]
Hey @OliPicard,

The documentation team are working hard on updating the docs for when the next gen libraries are released. While the next gen library is still in beta the docs will continue to refer to the current release version of the library.
