### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by Ofekmeister** [twilio/twilio-python#271]
https://www.twilio.com/docs/api/rest/making-calls#example-2

The 'from' fields don't match. I would have submitted a pull request but I was unable to find those docs. Also, these docs will be outdated when 6x becomes master.

**Comment by philnash** [comment]
Hi @Ofekmeister,

Do you mean that "+14158675309" (from the code) is not the same as "415-867-5309" from the description?

If so, they are the same number just different formats. "415-867-5309" is the national format in the US and "+14158675309" is the international, or E164 format which is [best for formatting international numbers in Twilio](https://www.twilio.com/help/faq/phone-numbers/how-do-i-format-phone-numbers-to-work-internationally).

You are right, the docs are not updatable from this repo. However, fear not, our docs team are preparing for the release of version 6 and the docs will be updated.

Let me know if this helps and we can close this issue. Thanks!

**Comment by Ofekmeister** [comment]
It looks like to docs changed it to example 1 [https://www.twilio.com/docs/api/rest/making-calls#example-1](url)

We have 415-867-5309, 415-555-1212, and 5017250604

**Comment by philnash** [comment]
You are absolutely correct! The docs are maintained separate to this repo, so I'm going to raise an issue in our internal bug tracker and close this. Hope that's ok.
