### ISSUE TITLE
Is there a way to validate a phone number by sms?

### ISSUE THREAD

**Issue by AungThiha** [twilio/twilio-python#272]

**Comment by philnash** [comment]
Hi @AungThiha,

How do you mean validate exactly?

Do you mean [verify a number with your account](https://www.twilio.com/help/faq/voice/how-do-i-add-a-verified-outgoing-caller-id-with-twilio)? Or [verify a number belongs to a user](https://docs.authy.com/phone_verification.html)?

Thanks.

**Comment by AungThiha** [comment]
I want to add phone numbers to my verified caller ids list.

1. I cannot find a way to send OTP(one time password/pin) to a user via sms.
2. When the user send back OTP to my server, I do not know how to verify it to my twilio account.

**Comment by philnash** [comment]
I'm afraid this is not possible by SMS. When verifying numbers for use with your account the [API only makes the call method available](https://www.twilio.com/docs/api/rest/outgoing-caller-ids#list-post).
