### ISSUE TITLE
Unable to change Twilio IP Messaging channel from public to private

### ISSUE THREAD

**Issue by Baisang** [twilio/twilio-python#275]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:** 5.4.0
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

### Code Snippet
```python
def make_channel_private(channel_unique_name):
    client = TwilioIpMessagingClient(ACCOUNT_SID, AUTH_TOKEN)
    service = client.services.get(sid=SERVICE_SID)
    channel = filter(lambda x: x.unique_name == channel_unique_name, service.channels.list())
    channel = channel[0]
    response = channel.update(type='private')
```

### Error
The channel type is not changed to private after a channel.update call

### Steps to Reproduce
1. Create a public channel
2. Have some users join the channel
3. Attempt to change the channel type to private and fail

**Comment by Baisang** [comment]
It's been 3 days without a response, and I've noticed that [some](https://github.com/twilio/twilio-python/issues/272) [other](https://github.com/twilio/twilio-python/issues/271) [people](https://github.com/twilio/twilio-python/issues/268) have raised issues about this library that have gone even longer without responses.

Is this repository still being maintained? If not, you probably shouldn't tell people to use it on your website, especially with such lacking documentation.

**Comment by philnash** [comment]
Hi @Baisang,

Apologies, this repo has not been kept watch on as best as we could do. It certainly is maintained and I will double down on efforts to get these issues looked at. I understand that it takes effort to raise bugs like this, so thank you for that and sorry we haven't responded in a timely manner.

Can I ask, do you get an error when you make this call, or does it respond successfully but just not change the type of the channel?

Thanks!

**Comment by Baisang** [comment]
@philnash, thanks for the response!

The call returns a `None` in python, and the channel in question is not updated. Here is a slightly more detailed example of what I meant:

``` python
def make_channel_private(channel_unique_name):
    client = TwilioIpMessagingClient(ACCOUNT_SID, AUTH_TOKEN)
    service = client.services.get(sid=SERVICE_SID)
    channel = filter(lambda x: x.unique_name == channel_unique_name, service.channels.list())
    channel = channel[0]
    response = channel.update(type=u'private')
    # get the channel again, so a fresh copy? i.e. type should be private
    channel = filter(lambda x: x.unique_name == channel_unique_name, service.channels.list())
    channel = channel[0]
    print str(channel.__dict__)
    print response
```

The output I get will be like:

```
{ 'large' : 'object', ... , u'type': u'public' }
None
```

Using `Type` instead of `type` in the kwargs has the same effect.

**Comment by philnash** [comment]
Thanks for the update, I'm just triaging this with the IP Messaging team to find out whether it's an underlying bug or an issue with this library. Will update when I find out.

**Comment by philnash** [comment]
Hey @Baisang,

So it turns out that this was an error in the documentation. It's not possible to change a channel from public to private. The [documentation has been updated already](https://www.twilio.com/docs/api/ip-messaging/rest/channels#update-a-channel) so I'm going to close this.

Thanks for reporting and sorry again for not getting back to you sooner.
