### ISSUE TITLE
[Bug] Default parameter for `proxy_rdns` seems to have been mis-set

### ISSUE THREAD

**Issue by alistair-broomhead** [twilio/twilio-python#284]
**Version: All**
**API Subdomain (api/taskrouter/ip_messaging): resources.connection**

The default parameter for `proxy_rdns` in [`httplib2.ProxyInfo.__init__`](https://github.com/httplib2/httplib2/blob/0.9.2/python2/httplib2/__init__.py#L751) is True, while the default parameter for `proxy_rdns` in [`twilio.rest.resources.connection.Connection.set_proxy_info`](https://github.com/twilio/twilio-python/blob/master/twilio/rest/resources/connection.py#L23) is `None`.

This causes somewhat unexpected behaviour in cases where dns lookup is not possible without going through the proxy.

I have opened https://github.com/twilio/twilio-python/pull/282 which contains a fix, simply changing the default parameter to match that of httplib2.

**Comment by alistair-broomhead** [comment]
Is there any chance we can get this looked at any time soon? Is this project active at all? It has been a couple of months since I opened the issue and pull request, and I'd have thought it was simple enough for a simple "yay"/"nay", or at last a "not yet"...

**Comment by efossier** [comment]
Hey we have a brand new version of the library built from the ground up. Please upgrade and reopen an issue if it doesnt fix the problem.
