### ISSUE TITLE
DateTime serialization next-gen

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-python#289]
**Version:** 6.0.0rc-12
**API Subdomain (api/taskrouter/ip_messaging):** monitor
### Code Snippet

``` python
events = client.monitor.events.list(
    source_ip_address="104.14.155.29",
    start_date=datetime(2015, 4, 25, tzinfo=pytz.UTC),
    end_date=datetime(2015, 4, 25, 23, 59, 59, tzinfo=pytz.UTC)
)
```

From this [page method](https://github.com/twilio/twilio-python/blob/next-gen/twilio/rest/monitor/v1/event.py#L161) I can see that date filters are been truncated to date only values even if a datetime is specified.

From the docs, date _Input is a UTC ISO 8601 Timestamp._ and this might be true for most filter params in `list()` methods for listResources.

**Comment by jingming** [comment]
This is done!
