### ISSUE TITLE
list filer does not work as expected

### ISSUE THREAD

**Issue by linusliu** [twilio/twilio-python#290]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**twilio (5.6.0)
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```python
for message in client.messages.list(date_sent <= datetime.date(2016,9,1)): 
```

### Exception / Log
```
for message in client.messages.list(date_sent <= datetime.date(2016,9,1)):                                                                                                                                                                     
NameError: name 'date_sent' is not defined

```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by MikeBenza** [comment]
@linusliu This is a bug in your code.  date_sent is a [parameter to the `list` function](https://github.com/twilio/twilio-python/blob/7441999259da82ceba0653fba1838f3c042f4a1d/twilio/rest/resources/messages.py#L125).  When you write `client.messages.list(date_sent <= datetime.date(2016,9,1))` Python is evaluating `date_sent <= datetime.date(2016,9,1)` first.  It's saying that `date_sent` isn't a variable that exists.  You're looking for the `before` parameter:

```
>>> from twilio.rest import TwilioRestClient
>>> client = TwilioRestClient(account_sid, auth_token)
>>> import datetime
>>> for message in client.messages.list(before=datetime.date(2015,12,1)):
...   print message.date_sent
...
2015-11-28 16:06:52
2015-11-28 16:00:32
2015-11-28 15:59:44
2015-11-28 15:49:02
2015-11-27 15:16:50
2015-11-27 14:37:26
2015-11-27 14:36:46
```
