### ISSUE TITLE
Inconsistent bdist_wheel versus sdist releases

### ISSUE THREAD

**Issue by adamchainz** [twilio/twilio-python#292]
Version 5.6.0 has only the sdist on PyPI: https://pypi.python.org/pypi/twilio
Version 5.5.0 has only the bdist_wheel: https://pypi.python.org/pypi/twilio/5.5.0

Please release both for each version. You can do this with `python setup.py clean sdist bdist_wheel upload`.

You could also run `python setup.py clean bdist_wheel upload` on the `v5.6.0` tag to upload the wheel for 5.6.0 now so peoples' builds can take advantage of it.

Thanks.

**Comment by efossier** [comment]
@adamchainz Thanks for the feedback, I've updated our release process to upload both an sdist and a bdist_wheel for future releases. 

We don't have the bandwidth to go back an re-release each version with both of them, I went ahead and uploaded a bdist for the latest version `6.1.0` as well as the version you mentioned `5.6.0`.

Please reply to this issue if you require a different version to be uploaded. In the meantime I will mark this as resolved.
