### ISSUE TITLE
access to media (mp3/wav files) behind recordings

### ISSUE THREAD

**Issue by smason** [twilio/twilio-python#296]
**Version: 6.0.0rc12**
**API Subdomain (api/taskrouter/ip_messaging): api/recordings**

I'm trying to use your new client libraries to pull (mp3) recordings out of your system.  I can't see any nice way of getting uri/urls of the files — personally I'm only interested in mp3s, but can't see how to get wavs either.

I'm currently doing:
```python
recording_sid = 'REcea44fe31…'

twilio_client = twilio.rest.Client(
  settings.TWILIO_ACCOUNT_SID,
  settings.TWILIO_AUTH_TOKEN)

recording_url = '{base}/2010-04-01/Accounts/{acct_sid}/Recordings/{rec_sid}.mp3'.format(
  base=twilio_client.api.base_url, acct_sid=twilio_client.account_sid, rec_sid=recording_sid)
```
as I can't find/see anything easier.  I can get somewhat close by doing
```python
twilio_client.api.absolute_url(twilio_client.account.recordings(recording_sid).fetch().uri)
```
but this requires an unnecessary `fetch` and just gets me to the json file rather than the recording itself.

I can see there's some code in `rest/resources/recordings.py`, but get the following when trying to import:
```
…site-packages/twilio/rest/exceptions.py in <module>()
      5 
      6 # Backwards compatibility.
----> 7 from ..version import __version__, __version_info__
      8 
      9 from ..exceptions import TwilioException

ImportError: cannot import name __version__
```

Any suggestions would be appreciated, thanks!

**Comment by goldsmith** [comment]
hey, did you ever figure out a better way of doing this?

**Comment by smason** [comment]
@goldsmith we're building the url's as I said.   Am using Twilio's rest library less and less and just doing it directly with the `requests` package.  The API endpoints seem to be more stable than the Python API so it's easier for us long term that way.

Their Python API is great exploratory/adhoc stuff in iPython/Jupyter, but `requests` (http://docs.python-requests.org/en/latest/) seems better suited for server side stuff, IMO!

**Comment by efossier** [comment]
@smason @goldsmith Thanks for bringing this to our attention, unfortunately this isnt supported in our library at the moment. The best workaround at the moment is what you came up with, to parse the url and add an `.mp3` at the end and download it with another http client such as requests.

I'll bring this up with the team and we'll think about how to solve this correctly in our library.

**Comment by kmrambo** [comment]
Any updates on this? Is this feature added?
