### ISSUE TITLE
No module name rest .

### ISSUE THREAD

**Issue by theparadoxer02** [twilio/twilio-python#311]
When i am running the code ,  i am getting the error :-

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "twilio.py", line 1, in <module>
    from twilio.rest import TwilioRestClient
ImportError: No module named rest
```

**Comment by efossier** [comment]
@theparadoxer02 the twilio.rest module does exist... https://github.com/twilio/twilio-python/tree/master/twilio/rest

However `TwilioRestClient` has been renamed to simply `Client` in the 6.x libraries
