### ISSUE TITLE
Just updated to twilio 6.0.0 and No module named 'twilio.util'

### ISSUE THREAD

**Issue by sktzofrenic** [twilio/twilio-python#321]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:6.0.0**
**Browser Softphone Capability Token:**

### Code Snippet
```python
from twilio.util import TwilioCapability  # This used to work
```

### Exception / Log
```
  File "app.py", line 5, in <module>
    from twilio.util import TwilioCapability
ImportError: No module named 'twilio.util'


```

### Steps to Reproduce
1. Try to import and it fails.

**Comment by sktzofrenic** [comment]
The reason I upgraded was to get the new fax functionality, but it does not appear to be in the new library update. Please let me know if I'm missing it.

**Comment by jingming** [comment]
@sktzofrenic Thanks for writing in!

1. `TwilioCapbility` has been moved here: https://github.com/twilio/twilio-python/blob/master/twilio/jwt/client/__init__.py

2. `Fax` features exist in the `alpha` line of the library as it is still a beta product: https://github.com/twilio/twilio-python/blob/alpha/twilio/rest/fax/__init__.py
The latest version there is `6.0.0a1`.

**Comment by sktzofrenic** [comment]
Alright that solved that one, now where did you move this module? 

`from twilio.rest import TwilioRestClient  # also prodcues error`

**Comment by jingming** [comment]
yes, `username` and `password` can be `account_sid` and `auth_token`. They were renamed because `account_sid` and `auth_token` is not the only method you can use to auth.

**Comment by sktzofrenic** [comment]
Unfortunately the whole thing crashed my app. Too many breaking changes and not enough documentation. I don't the twilio JS client is setup for the new changes. Even the public beta version could not recognize the capability tokens generated by the new python ClientCapabilityToken generator. So since none of my clients could authenticate it's basically unusable in the current state. 

I am looking forward to these updates though.

**Comment by efossier** [comment]
@sktzofrenic you shouldnt be calling the _generate_token method, you should call `to_jwt` i believe.

**Comment by efossier** [comment]
For anyone else having issues migrating to the new version, we have a guide to update your app to the new 6.x library: https://www.twilio.com/docs/libraries/python/migration-guide

**Comment by anotherstarburst** [comment]
@efossier just a note that the migration guide doesn't specify anything about the util /  TwilioCapability breaking change

**Comment by anotherstarburst** [comment]
For anyone reading this, it looks like this page details the usage of the new class https://www.twilio.com/docs/guides/client/capability-tokens - from what I can see you import and use
  
    from twilio.jwt.client import ClientCapabilityToken

In the same way as TwilioCapability
