### ISSUE TITLE
Lookups in new version?

### ISSUE THREAD

**Issue by remik** [twilio/twilio-python#326]
How to trigger lookup in new version?

**Version:**
6.0.0

### Old version
```python
client.phone_numbers.get('+1.....', include_carrier_info=True)
```

New version doesn't have `include_carrier_info` and is not doing any lookup. What is new syntax to get carrier info?

**Comment by efossier** [comment]
The new library models the rest api very closely so you would do:
```python
client.api.v2010.account('account').available_phone_number.local('+1....')
```

**Comment by remik** [comment]
Lookup is not for checking number before buy but get details about it.
Did you remove this support? 
https://www.twilio.com/lookup

**Comment by TiernanKennedy** [comment]
Carrier lookups seem to be broken in 
Version: 6.0.0

From the source this seems to be the accepted method:
```
client = Client(account_sid, auth_token)
client.lookups.v1.phone_numbers(
    phone_number='+xxxxxxxxx'
).fetch()
```

The old method was:
```
client = Client(account_sid, auth_token)
client.lookups.phone_numbers.get(
                '+xxxxxxxx',
                include_carrier_info=True
            )
```

This returned a payload that had the correct carrier. 

All tests I've done with v6 are returning `None` for carrier. v5 is still working.

Can someone clarify what's going on here? @remik did you find the correct way?

**Comment by remik** [comment]
I felt they ignored me so I did it myself with requests:

```
import requests
TWILIO_LOOKUP_URL = "https://lookups.twilio.com/v1/PhoneNumbers/{number}?Type=carrier"
TWILIO_ACCOUNT = "ACxxxx"
TWILIO_TOKEN= "xxx"
response = requests.get(TWILIO_LOOKUP_URL.format(number=number),
                        auth=(TWILIO_ACCOUNT, TWILIO_TOKEN))
carrier =  response.json()['carrier'] if response.status_code == requests.codes.ok else {}
```

**Comment by TiernanKennedy** [comment]
Well that's annoying - defeats the purpose of the library.

@efossier any plans to support this in v6?
