### ISSUE TITLE
Changelogs and documentation do not reflect breaking changes - ImportError: cannot import name TwilioRestClient

### ISSUE THREAD

**Issue by microwavedboy** [twilio/twilio-python#331]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

The 6.0.0 documentation and changelog do not indicate major breaking changes with the Twilio-Python bindings. 

**Version:**
6.0.0
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```python
# paste code here
from twilio.rest import TwilioRestClient
```

### Exception / Log
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name TwilioRestClient
```

### Steps to Reproduce
1. Install twilio-python `pip install twilio`
2. Follow a documentation example that includes the directive `from twilio.rest import TwilioRestClient` such as http://twilio-python.readthedocs.io/en/latest/usage/basics.html
3.

**Comment by efossier** [comment]
@microwavedboy Thanks for bringing that to our attention! It does look like the docs provided on readthedocs are out of date. I'll look into updating those.

Please look at the README.md and other documentation hosted on twilio.com (https://www.twilio.com/docs/libraries/python) to get up to date information about the library. If you want a migration guide from the 5.x.x libraries take a look at this page: https://www.twilio.com/docs/libraries/python/migration-guide

**Comment by microwavedboy** [comment]
Ah, thanks for that link to the upgrade docs, @efossier  -- https://github.com/twilio/twilio-python#migrate-from-5x seems like it's got a TBD / placeholder link space on it.

**Comment by efossier** [comment]
@microwavedboy I think we were trying to link to the UPGRADE.md, however that doesnt contain information to migrate from 5.x to 6.x, I'll change it to point to that migration guide I linked earlier.

**Comment by KrunchMuffin** [comment]
1 year and 8 months later and the RTD site has not been updated! I spent 30mins trying to figure out what was wrong with my code. If you aren't going to update it, please delete it or state at the top of every page that it is for v5.
https://twilio-python.readthedocs.io
