### ISSUE TITLE
KeyError raised when accessing participants

### ISSUE THREAD

**Issue by willhardy** [twilio/twilio-python#333]
**Version:** 6.1.0
**API Subdomain:** api/account/conference

### Code Snippet
```python
    for p in conference.participants.list():
        pass
```

### Exception / Log
```
  File "twilio/rest/api/v2010/account/conference/participant.py", line 190, in list
    page_size=page_size,
  File "twilio/base/version.py", line 183, in stream
    for record in page:
  File "twilio/base/page.py", line 42, in __next__
    return self.next()
  File "twilio/base/page.py", line 48, in next
    return self.get_instance(next(self._records))
  File "twilio/rest/api/v2010/account/conference/participant.py", line 298, in get_instance
    conference_sid=self._solution['conference_sid'],
  File "twilio/rest/api/v2010/account/conference/participant.py", line 443, in __init__
    'status': payload['status'],
```

### Steps to Reproduce
1. Connect to live API
2. Access a participant
3. `KeyError`

The current API only returns the following fields, there is no `status` field:
```
            "conference_sid"
            "account_sid"
            "call_sid"
            "muted"
            "hold"
            "end_conference_on_exit"
            "start_conference_on_enter"
            "date_created"
            "date_updated"
            "uri"
```
(Last checked April 27)

**Comment by efossier** [comment]
@willhardy Thanks for writing in, we've identified the issue and are working with the team to come up with a fix.

**Comment by Germaniero** [comment]
Any update? This bug blocks my project migration to 6.x.

**Comment by efossier** [comment]
@Germaniero yeah we probably will get to it within a week or two. Thanks for your patience, we have an usually high work load at the moment due to our upcoming developer conference Signal on May 24th.

**Comment by efossier** [comment]
@Germaniero We pushed a fix to the api this afternoon so your code should now work without having to update the library. Feel free to reopen this if the issue persists and we'll take a second look.
