### ISSUE TITLE
For outgoing caller ids, create option is missing.

### ISSUE THREAD

**Issue by santhiyaa** [twilio/twilio-python#351]
For outgoing caller ids, there is no option to create new caller ids. Twilio provides a POST api to create them.

**Comment by jmctwilio** [comment]
The option is supported under `cilent.validation_requests` since it returns a different payload.

This is definitely an oddity.  It's a side effect of the structure of the API.  The team is evaluating a better way to surface, document, and even name this to enhance discoverability.
