### ISSUE TITLE
when listing calls, the "status" parameter gives syntax warning

### ISSUE THREAD

**Issue by actioncrypto** [twilio/twilio-python#352]
**Version:** 6.3.0
**API Subdomain (api/taskrouter/ip_messaging):** calls/list filtering

### Code Snippet
```import datetime
clist = twilioclient.calls.list(to='+15558675309', start_time=datetime.datetime.utcnow().date(), status='completed')
```

### Steps to Reproduce
1. just look at the code completion in an IDE, and it will yell that it expects a `CallInstance.Status` type for the `status` param, when it should really be fine with a vanilla string. It works fine with string, but code completion gives parser error because the docstring is saying otherwise...

**Comment by jmctwilio** [comment]
Thanks for the report, we'll look into alternatives to provide a more intuitive interface.

**Comment by jmctwilio** [comment]
@actioncrypto Unfortunately, this is generated code and the change is fairly complicated.  We'll add a ticket to clean it up, but it's likely going to take a while as there are other requirements that are more pressing.
