### ISSUE TITLE
Error fetching channel by unique name (mismatch with SID)

### ISSUE THREAD

**Issue by learykara** [twilio/twilio-python#354]
**Version:**
6.3.0
**API Subdomain (api/taskrouter/ip_messaging):**
api/ip_messaging/channels

### Code Snippet
```python
from twilio.rest import Client
client = Client(os.environ.get('TWILIO_API_SID'), os.environ.get('TWILIO_API_SECRET'))
service = client.ip_messaging.services.get(sid=os.environ.get('TWILIO_CHAT_SERVICE_SID'))
channel = service.channels.get(sid='dev-343').fetch()
print channel.sid
# => u'CHxxxxxxxxxxxxxxxxxxxxxx'
print channel.unique_name
# => u'dev-343'

message_body = {'type': 'text'}
message = {'from_': 123456, 'body': json.dumps(message_body)}
channel.messages.create(**message)

"""
Result:
TwilioRestException:
HTTP Error Your request was:

POST /Services/ISbea8990fd0d846a8b1c324084d6756f8/Channels/devo-343/Messages

Twilio returned the following information:

Unable to create record: The requested resource /Services/ISbea8990fd0d846a8b1c324084d6756f8/Channels/devo-343/Messages was not found

More information may be available here:

https://www.twilio.com/docs/errors/20404
"""
```
### Issue
When fetching a channel via it's unique name as above, the correct channel is located with all expected values in `channel.sid`, etc. However `channel._uri` incorrectly resolves to `/Services/{service_sid}/Channels/{unique_name}`, when it should be `/Services/{service_sid}/Channels/{sid}` [here](https://github.com/twilio/twilio-python/blob/master/twilio/rest/ip_messaging/v2/service/channel/__init__.py#L276).  This causes a 404 when attempting to get or post messages, members, etc that are instantiated from the values in `channel._solution` (such as [here](https://github.com/twilio/twilio-python/blob/master/twilio/rest/ip_messaging/v2/service/channel/__init__.py#L370) -- in this case `MessageList._uri` ends up as `/Services/{service_sid}/Channels/{unique_name}/Messages` [here](https://github.com/twilio/twilio-python/blob/master/twilio/rest/ip_messaging/v2/service/channel/message.py#L38)).

Note that we ran into this problem in upgrading from v5.7.0 to 6.3.0, so it seems that fetching a channel by unique name used to not create any issues.

We are able to hack around the problem by explicitly setting ```channel._proxy._solution['sid'] = channel.sid```

### Steps to Reproduce
1. Fetch a channel by its unique name
2. Attempt to post a message to that channel's message list

**Comment by efossier** [comment]
@learykara Good catch! We've created a ticket to track this bug and will be prioritizing soon.

**Comment by jmctwilio** [comment]
Closing issue in favor of ticket.
