### ISSUE TITLE
pysocks installed in py2.7

### ISSUE THREAD

**Issue by tisdall** [twilio/twilio-python#356]
**Version: 6.3.0**

I was updating my copy of twilio from 5.6.0 and noticed that it also brought in `PySocks`.  I looked at the `setup.py` and it looks like it should only be doing that in py3k.  I guess it's a minor issue as I suspect the code won't use the pysocks components in py2.7, but I'm managing pinning lib versions for a project and it's yet another library to manage.

Did I get it right?  Is it installing pysocks on 2.7 a mistake?

**Comment by ilanbiala** [comment]
@tisdall I installed the library using Python 2.7 from scratch and didn't download pysocks. I'm not sure how you have it installed, but try running a clean install again and if it happens paste the installation log from your terminal here.

**Comment by tisdall** [comment]
I have a `requirements.txt` file with packages pinned to particular versions.  I changed `twilio==5.6.0` to `twilio==6.3.0` and installed via `pip install -r requirements.txt`.  I got the following output:

```
Collecting pysocks (from twilio==6.3.0->-r requirements.txt (line 34))
  Downloading PySocks-1.6.7.tar.gz (282kB)
    100% |████████████████████████████████| 286kB 2.0MB/s 
```

I tried downgrading it back to 5.6.0, removing pysocks, and then upgrading again.  I get the same result each time, pysocks is installed due to twilio.

I'm using pip 8.1.2 (not sure if that makes a difference).  I also tried turning up the verbosity in pip but that didn't give any hints about why it's doing this (it mostly just outputted all the files it found on pypi).

I also tried removing `cryptography` to see if it would properly install that on installing 6.3.0 and it seems to do that properly.

**Comment by tisdall** [comment]
I created a fresh virtualenv with py2.7 and got this:
```
$ env/bin/pip install "twilio==6.3.0"
Collecting twilio==6.3.0
  Downloading twilio-6.3.0-py2.py3-none-any.whl (731kB)
    100% |████████████████████████████████| 737kB 935kB/s 
Collecting PyJWT>=1.4.2 (from twilio==6.3.0)
  Downloading PyJWT-1.5.0-py2.py3-none-any.whl
Collecting six (from twilio==6.3.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from twilio==6.3.0)
  Downloading requests-2.18.1-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 2.6MB/s 
Collecting pytz (from twilio==6.3.0)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 1.2MB/s 
Collecting pysocks (from twilio==6.3.0)
  Downloading PySocks-1.6.7.tar.gz (282kB)
    100% |████████████████████████████████| 286kB 1.4MB/s 
Collecting idna<2.6,>=2.5 (from requests>=2.0.0->twilio==6.3.0)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 3.3MB/s 
Collecting urllib3<1.22,>=1.21.1 (from requests>=2.0.0->twilio==6.3.0)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
    100% |████████████████████████████████| 133kB 1.5MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->twilio==6.3.0)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.8MB/s 
Collecting certifi>=2017.4.17 (from requests>=2.0.0->twilio==6.3.0)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 1.3MB/s 
Building wheels for collected packages: pysocks
  Running setup.py bdist_wheel for pysocks ... done
  Stored in directory: /home/tim/.cache/pip/wheels/8a/24/d0/6c9c780e6d7fbd5cc6ffaa83b926ffc186886a5bad16078bc7
Successfully built pysocks
Installing collected packages: PyJWT, six, idna, urllib3, chardet, certifi, requests, pytz, pysocks, twilio
Successfully installed PyJWT-1.5.0 certifi-2017.4.17 chardet-3.0.4 idna-2.5 pysocks-1.6.7 pytz-2017.2 requests-2.18.1 six-1.10.0 twilio-6.3.0 urllib3-1.21.1
```
That's using the latest version of pip.

**Comment by dahlia** [comment]
It's because the wheel (twilio-6.3.0-py2.py3-none-any.whl) on the PyPI was built using Python 3.6.  Since wheels don't include setup.py but the static list of requirements, the recent versions of pip install the package with dependencies for Python 3.6 regardless of the Python version.

In the same reason, cryptography/idna/pyOpenSSL won't be installed together with twilio on Python 2.  Even though they are required on Python 2.

There could be two solutions.  The first one is to remove twilio-6.3.0-py2.py3-none-any.whl file on the PyPI so that pip executes setup.py to dynamically build the list of requirements every time it install twilio.

Another one is to utilize [environment markers introduced by PEP 508][1].  It would look like:

~~~python
setup.py(
    ...,
    extras_require={
        ":python_version<'2.6'": ['simplejson'],
        ":python_version<'3.0'": ["cryptography >= 1.3.4", "idna >= 2.0.0", "pyOpenSSL >= 0.14"],
        ":python_version>='3.0'": ['pysocks'],
    }
)
~~~

[1]: https://www.python.org/dev/peps/pep-0508/#environment-markers

**Comment by dahlia** [comment]
Sent a pull request to fix this: #357.

**Comment by tisdall** [comment]
Ah..  I saw the `setup.py` and was wondering why it wasn't working the way it was intended.  Thanks for the explanation!

**Comment by ilanbiala** [comment]
@tisdall @dahlia could you try downloading version 6.4.3 and seeing if this issue still persists?

**Comment by ilanbiala** [comment]
Closing as we believe that this issue has been fixed in the latest version, but please feel free to comment if there are still issues and we'll reopen.

**Comment by tisdall** [comment]
@ilanbiala - It seems to be good!  However https://pypi.python.org/pypi/twilio is still pointing to 6.4.3a1 . I see the latest release on https://pypi.python.org/simple/twilio/ and pip installs the latest correctly, too.

**Comment by ilanbiala** [comment]
@tisdall sorry about that, it should be fixed now. Thanks for bringing that up by the way!
