### ISSUE TITLE
Searching for phone numbers with fax capability

### ISSUE THREAD

**Issue by mumumumu** [twilio/twilio-python#363]
**Version: 6.3.0a1**

### Feature Request
I want to search and purchase phone numbers with faxing, sms, and mms enabled. Currently I'm only able to search for numbers with sms and mms enabled. Will searching for fax enabled numbers be coming down the line in the alpha branch?

**Comment by jmctwilio** [comment]
@mumumumu 

Excellent request.  In fact, with the push to finalize the auto-generation of the libraries, all of the fields supported by the numbers team will soon be exposed on the helper libraries.  I can't provide an exact time to expect it, but it should be very soon.
