### ISSUE TITLE
AttributeError when creating Notify service via client.notify.services()

### ISSUE THREAD

**Issue by mhb11** [twilio/twilio-python#374]
I'm trying to create a binding for an SMS-related notify service in Twilio (Python SDK, v 6.4.3), but it keeps giving me an `AttributeError`. The details are as follows:

**Version: 6.4.3**
**API Subdomain: Notify api**

```
from twilio.rest import Client
from myproj.twilio_settings import ACCNT_SID, AT, SERV_SID

client = Client(ACCNT_SID, AT)

service = client.notify.services(SERV_SID)

def bind_user_to_twilio_notify_service(user_id,phone_number):
    binding = service.bindings.create(
        identity=user_id,
        binding_type='sms',
        address=phone_number,
    )
    print(binding.sid)
```

I get an AttributeError like so: 

> AttributeError: 'Client' object has no attribute 'notify'

Likewise, using `service = client.notifications.v1.services(SERV_SID)` doesn't work either. I get:

> AttributeError: 'NotificationList' object has no attribute 'v1'

**Comment by mhb11** [comment]
I found out that since `Notify` is currently available in public beta only, it's supported only by the alpha version of helper libraries. I.e. I'll need to do the following to fix the situation:

`pip install twilio==6.4.3a1 `

**Comment by smartyram** [comment]
Thanks @mhb11 you saved me hours. Twilio +1 for keeping this a secret and wasting precious developer time.

**Comment by imthepitts** [comment]
Hello @smartyram, 

Zack with Twilio Support here. Apologies for the confusion this caused. As of release 6.5.0 (July 27) all beta features such as Notify are included in the main artifact, and the alpha branch has been discontinued:

https://github.com/twilio/twilio-python/releases/tag/6.5.0 

If you update your local installation of the helper library to the latest, you'll pick up all the features and updates for Notify.

If you run into further issues, please let us know or reach out to the support team:
https://www.twilio.com/console/support/tickets/create 

All the Best,
Zack
