### ISSUE TITLE
Django helpers

### ISSUE THREAD

**Issue by km-pg** [twilio/twilio-python#389]
I was wondering if you guys might be willing to pull in the django helper code from django-twilio. It appears that django-twilio isn't being maintained as it hasn't been updated for version 6 of the twilio library.
https://github.com/rdegges/django-twilio

**Comment by jingming** [comment]
@km-pg Thanks you for your request. `django-twilio` is not officially supported and due to the large number of platforms that the library is geared to support, we feel that it is unwise to add something that would add clutter to other applications.
