### ISSUE TITLE
create a push credentials failed

### ISSUE THREAD

**Issue by cchuang6** [twilio/twilio-python#391]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
6.5.2
### Code Snippet
```python
credential = client.notify.credentials.create(type="APN",
                                              friendly_name="test cred",
                                              certificate=IOS_PUSH_SANDBOX_CERT,
                                              private_key=IOS_PUSH_SANDBOX_KEY, 
                                              sandbox="true")

```

### Exception/Log
```
TwilioRestException: 
HTTP Error Your request was:

POST /Credentials

Twilio returned the following information:

Unable to create record: Could not parse certificate

More information may be available here:

https://www.twilio.com/docs/errors/20001

```

### Steps to Reproduce
I tried to create a push credential  by using iOS certificate and private key. I tried to do it on the web and there is no problem to generate a new one. However, when I tried to create one by using notify credential API, it failed. Could you please help me ? What kind of format of the certificate and the private key should I pass ?

Thanks

**Comment by jingming** [comment]
@cchuang6 Please redirect this question to help@twilio.com. We have a wonderful support team that would be happy to assist you!
