### ISSUE TITLE
Request validator broken with HTTPS requests containing port numbers

### ISSUE THREAD

**Issue by thomasst** [twilio/twilio-python#392]
According to https://www.twilio.com/docs/api/security#notes the port number should be omitted in HTTPS requests for signature validation. `RequestValidator.validate` should take these rules into account and not require the user to strip out the number.

My current workaround is to parse and reencode the URL as follows, but this should happen within the `validate()` method:
```
parsed = urlparse.urlparse(uri)
if parsed.scheme == 'https':
    parsed = parsed._replace(netloc=parsed.netloc.split(':')[0])
    uri = parsed.geturl()
```

Internal ticket: https://www.twilio.com/console/support/tickets/1061656

**Comment by Brodan** [comment]
Just opened a PR for this fix @jingming @thomasst 
#394

**Comment by efossier** [comment]
We'll get it out in the next release.

**Comment by efossier** [comment]
This is in release `6.8.1`
