### ISSUE TITLE
client.messages.page() throws an Exception requiring PageToken

### ISSUE THREAD

**Issue by parthi82** [twilio/twilio-python#395]
**Version:** twilio (6.7.1)

### Code Snippet
```python
     message_page = client.messages.page(page_number=0, page_size=100) # works
     message_page1 = client.messages.page(page_number=1, page_size=100) # throws exception
```

### Exception/Log
```
TwilioException: ('Unable to fetch page', HTTP 400 {"code": 20001, "message": "PageToken is required for paging.", "more_info": "https://www.twilio.com/docs/errors/20001", "status": 400})
```

### Steps to Reproduce
1. call the client.messages.page() function passing "page_number" argument as 1 or anything greater than 0

The page function for accounts works without throwing any Exception when called the same way 
without passing any page_token
```python
     account_page = client.api.accounts.page(page_number=0, page_size=100) # works
     account_page1 = client.api.accounts.page(page_number=1, page_size=100)  # works
```

**Comment by Brodan** [comment]
I was able to reproduce this. After digging through the code for a while this looks like something that can only be handled on Twilio's end and is not an issue with the helper library.

**Comment by jmctwilio** [comment]
@parthi82 Great catch!  Twilio supported absolute paging a long while ago and the parameter of `page_number` was maintained for legacy reasons.  The approach we take to paging now (and for over two years now) is relative paging which requires page tokens.  Depending on how you want to page through results, there are methods like `.list()` and `.stream()`.  Additionally, for your use example here, you should be able to get `message_page.next_page()`.  

https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

We'll add a ticket to try and bury it more or update the comments to let folks know that they shouldn't be using it.
