### ISSUE TITLE
make twilio client work behind a proxy without a horrible hack

### ISSUE THREAD

**Issue by hjwp** [twilio/twilio-python#409]
cf  #327 -- if a user is behind a proxy, the current "recommended" solution is a moderately hideous hack involving copy-pasting your own HttpClient class

https://stackoverflow.com/questions/43597379/how-to-provide-proxy-information-to-twilio-api-with-python/43608637#43608637

requests itself works quite happily with proxy servers by auto-detecting the `http_proxy` and `https_proxy` environment variables, it would be nice if that still worked for requests-as-used-by-twilio.

(disclosure: i work at [pythonanywhere](https://www.pythonanywhere.com/);  our free users have to go via our proxy for internet access. we set the standard env vars, so this "just works" for requests, and most 3rd party api tools, but twilio is one of the exceptions.)

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by thehackercat** [comment]
+1s

**Comment by childish-sambino** [comment]
Do env vars not work?

https://2.python-requests.org/en/master/user/advanced/#proxies

**Comment by thehackercat** [comment]
@childish-sambino it works, but there are some cases that we only want to request twilio behind a http proxy, instead of a global env setting, I prefer to set proxy in twilio-client

**Comment by childish-sambino** [comment]
Ah, makes sense. I'll check out the PR then.

**Comment by childish-sambino** [comment]
Fixed by #500
