### ISSUE TITLE
No module named twilio

### ISSUE THREAD

**Issue by toogoodbruh** [twilio/twilio-python#412]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
6.10.4

### Code Snippet
```python
from twilio.rest import Client
```

### Exception/Log
```
   from twilio.rest import Client
ModuleNotFoundError: No module named 'twilio'
```

I have tried following solutions to people asking the same question, but I still get the error. I have tried uninstalling python, pip and twilio and still get this error. I have spent 5 hours trying to fix this, but have got no where.

**Comment by JSkier21** [comment]
It doesn't appear that the module installed. Are you using python2 or 3? How did you install with pip? Output of pip show twilio?

**Comment by brenouchoa** [comment]
i had the same error and solved by checking that i had a twillio.py file on my path...

**Comment by raresmosescu** [comment]
Have you found the solution? I get the same error. Tested the code with 3.6.5 and 2.7.15 and still not working

**Comment by raresmosescu** [comment]
@GregKaleka I solved the issue. For the ones that are still having problems this is how I got rid of the problem: 

I downgraded the pastebin to pastebin-1.1.0 using this line of code in cmd: `pip install --user pastebin==1.1.0` , then I tried to run it again and it didn't work for some reason with the Thonny IDE. I tried it directly from cmd and it worked with both 2.7.15 and 3.6.5 which before both were having problems. 

Also I have updated pip before to the latest version and reinstalled the twilio package, but I don't think it helped with anything.

**Comment by amolngt** [comment]
my python version id 3.6.4 .. still no working

Traceback (most recent call last):
  File "send_sms.py", line 1, in <module>
    from twilio.rest import TwilioRestClient
ModuleNotFoundError: No module named 'twilio'

**Comment by hanumancode** [comment]
try: pip install twilio

**Comment by hanumancode** [comment]
try this: sudo pip3 install twilio --upgrade

**Comment by bsundar21** [comment]
Hell All 

I have been facing similar issues w twilio. 

**root**:~# sudo pip3 install twilio --upgrade
sudo: pip3: command not found
**root**~# sudo pip3 apt install twilio --upgrade
sudo: pip3: command not found
**root**:~# sudo apt pip3 install twilio --upgrade
E: Invalid operation pip3
**root**:~# sudo apt install twilio --upgrade
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
**root**:~# sudo apt install twilio
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by bsundar21** [comment]
I got this figured out 
I had Anaconda3 installed and twilio came in as a package in that where as i was trying to import twilio in to my idle enviroment which was not liked to Anaconda.

**Comment by blairg23** [comment]
Do `pip freeze | grep twilio` and ensure that you have it installed.

**Comment by brydavis** [comment]
Same error and similar set up to @bsundar21 

Was using Jupyter Notebooks to run (and failing to import).

Works fine when I ran from command line.

Strange...

**Comment by gothboiclique** [comment]
> try this: sudo pip3 install twilio --upgrade

This worked amazingly. Just had to remove sudo <3

**Comment by arun-natarajan-sudo** [comment]
> try this: sudo pip3 install twilio --upgrade

it worked for me. thanks buddy
