### ISSUE TITLE
Add Support for Python 3 async calls

### ISSUE THREAD

**Issue by Crandel** [twilio/twilio-python#415]
Please add posibility to send async requests. Right now your library block my event loop

**Comment by tstirrat15** [comment]
[There are ways to make synchronous calls asynchronous](https://stackoverflow.com/questions/44745642/wrapping-synchronous-requests-into-asyncio-async-await). Async and synchronous functions in python are largely incompatible - making this library async-compatible would break it for the synchronous use case.

**Comment by Crandel** [comment]
You just need to split http client from logic and add a possibility to replace the client into async client. You have a very tied architecture.

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by muzhig** [comment]
any news?

**Comment by cglacet** [comment]
Until this is possible is it possible, in the mean time, to build URLs and read responses independently of emitting actual  HTTP requests? I'm not familiar at all with the code (and not even with twilio that I only used for few hours) so I can't tell myself sorry. But if these two things are possible, maybe the best idea is to never emit HTTP request yourself and let that part to the user.

Maybe I'm wrong but I feel like this library is "just" a wrapper that build URL -> send HTTP -> parse the response? If that the case it should be very easy to transform synchronous calls to asynchronous calls (I guess there is a single place in the code that you should split in two, that's where the HTTP request is sent)?

**Comment by skrivanos** [comment]
Been a couple of years, any work still planned here?

**Comment by Hunga1** [comment]
Support for making async requests has been added and will be ready in the next release candidate.

#676
