### ISSUE TITLE
ImportError at / cannot import name Session

### ISSUE THREAD

**Issue by newbieShreve** [twilio/twilio-python#419]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

### Code Snippet
```python
from request import Request,Session,hooks
```

### Exception/Log
Request Method: | GET
-- | --
http://35.171.142.166/
1.11.4
ImportError
cannot import name Session
/var/www/polar/venv/local/lib/python2.7/site-packages/twilio/http/http_client.py in <module>, line 1
/var/www/polar/venv/bin/python
2.7.12
['/var/www/polar',  '/var/www/polar/venv/lib/python2.7',  '/var/www/polar/venv/lib/python2.7/plat-x86_64-linux-gnu',  '/var/www/polar/venv/lib/python2.7/lib-tk',  '/var/www/polar/venv/lib/python2.7/lib-old',  '/var/www/polar/venv/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/var/www/polar/venv/local/lib/python2.7/site-packages',  '/var/www/polar/venv/lib/python2.7/site-packages']
Thu, 31 May 2018 10:37:15 -0400

Exception Type: | ImportError
-- | --

It seems there is no Session object in request or hooks.  I am a bit confused.  This worked locally when i tested it, only issue is with putting it om my EC2 AWS server.

### Steps to Reproduce
1.installed twilio
2.import statement into views.py(this worked)
3.added test code and got this error

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by childish-sambino** [comment]
Hmm, which version of this lib are you using and how are you installing it?
