### ISSUE TITLE
Document backwards-incompatible changes

### ISSUE THREAD

**Issue by gavinwahl** [twilio/twilio-python#427]
The changelog needs to mention when there are backwards-incompatible changes. Version 6 breaks user code, but you wouldn't know it by reading the changelog when upgrading.

**Comment by eshanholtz** [comment]
Hi @gavinwahl 

The Twilio helper libraries use a modified version of Semantic Versioning in the form of `MAJOR.MINOR.PATCH`. In summary, `MINOR` rolls _may_ introduce breaking changes, and `MAJOR` version rolls indicate that extensive reworking would be required for an upgrade. Breaking changes are now also captured in the release notes. For more details, please refer to our [versioning strategy](https://github.com/twilio/twilio-python/blob/master/VERSIONS.md) and the [official migration guide](https://www.twilio.com/docs/libraries/python/usage-guide) for upgrading to 6.x.
