### ISSUE TITLE
Typeo SessionInstance Status

### ISSUE THREAD

**Issue by yonatancohen** [twilio/twilio-python#435]
There's a type in the following snippet,
it should be "in-progress"

**Version: 6.14.9 **

### Code Snippet
```    
class SessionInstance(InstanceResource):
class Status(object):
        IN_PROGESS = "in-progess"
```
=

**Comment by childish-sambino** [comment]
Fixed as part of the [6.22.0](https://github.com/twilio/twilio-python/releases/tag/6.22.0) release.
