### ISSUE TITLE
Twilio outbound call is not working after 2 minutes

### ISSUE THREAD

**Issue by pk402** [twilio/twilio-python#441]
this issue already asked here(https://stackoverflow.com/questions/49302108/twilio-call-automatically-cuts-after-2-minutes) but still not a valid answer is there.

I am also getting the same issue twilio call automatically cuts after 2 minutes.

Here is my `VoiceResponse` data.

```
<Response>
  <Say loop="1">Record Your message.</Say>
  <Record action="http://example.com/api/voice/record.xml" maxLength="3600" timeout="50"/>
</Response>
```
Here is the document: https://www.twilio.com/docs/voice/twiml/record

Please guide what i am missing.

**Comment by imthepitts** [comment]
Hi again, @pk402. As I mentioned in your previous issue #440, this is not a helper library issue. You'll need to contact Twilio Support directly to investigate.

GitHub issues should only be filed for bugs in the helper library code base, not for issues with the back-end service.

Please contact Twilio Support here: https://www.twilio.com/help/contact 

All the Best,
Zack

**Comment by pk402** [comment]
Thanks for your response.
I have already asked them , no repose so far in last 24 Hr.
Please can you help me.
