### ISSUE TITLE
Feature to pass custom parameters to ios / android / js client

### ISSUE THREAD

**Issue by parthi82** [twilio/twilio-python#449]
**Version:** 6.19.0

Is passing custom parameters to ios / android / js via Twiml supported in this release?. 
### Code Snippet
```
<Response>
  <Dial>
    <Client>
      <Identity>alice</Identity>
      <Parameter name="foo" value="bar"/>
      <Parameter name="baz" value="123"/>
    </Client>
  </Dial>
</Response>

```
the release notes mentions about custom parameters
https://github.com/twilio/twilio-python/releases/tag/6.19.0

can't find any documentation on how to do it.

**Comment by eshanholtz** [comment]
https://www.twilio.com/docs/libraries/reference/twilio-python/6.19.0/docs/source/_rst/twilio.twiml.html#twilio.twiml.voice_response.Client
