### ISSUE TITLE
how to confirm send sms status in django?

### ISSUE THREAD

**Issue by jingwangnet** [twilio/twilio-python#452]

**Comment by jingwangnet** [comment]
question as title?
i only find aticle about flask use fallback in doc.twilio.com.
no post about django use fallback .

**Comment by blairg23** [comment]
Bro, read the docs and use the Python example code.

https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource

Use "status_callback" parameter and set it to a URL you created in your Django app's url.py file (handle the logic in the corresponding views.py file)

**Comment by jingwangnet** [comment]
thanx. bro i got it

----------

该邮件从移动设备发送














--------------原始邮件--------------
发件人："Blair Gemmer "<notifications@github.com>;
发送时间：2019年3月2日(星期六) 凌晨3:27
收件人："twilio/twilio-python" <twilio-python@noreply.github.com>;
抄送："jing.wang "<admin@jingwangnet.com>;"Author "<author@noreply.github.com>;
主题：Re: [twilio/twilio-python] how to confirm send sms status in django? (#452)
-----------------------------------

 
Bro, read the docs and use the Python example code.
 
https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource
 
Use "status_callback" parameter and set it to a URL you created in your Django app's url.py file (handle the logic in the corresponding views.py file)

**Comment by eshanholtz** [comment]
It looks like you got the help you needed, so I'm going to go ahead and close this issue.
