### ISSUE TITLE
TwilioHttpClient does not support timeout in constructor

### ISSUE THREAD

**Issue by joninvski** [twilio/twilio-python#460]
**Version:** 6.26.1

### Feature Request

The `TwilioHttpClient` constructor does not support a `timeout` parameter. This makes it more troublesome for clients to configure a maximum time requests should wait for replies from twilio.

Does it seem ok to add a timeout parameter (defaults to `None` as it is working today) to the `TwilioHttpClient`. In ruby we have this option: https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/http/http_client.rb#L11

If i have your :+1: i'll work on this and open the PR.

Note: This is the PR that added the functionality to the ruby library: https://github.com/twilio/twilio-ruby/pull/339

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
@joninvski Sure, if you can submit a PR we'll take a look!

**Comment by Kerl1310** [comment]
Opened a [PR ](#484 )for this
