### ISSUE TITLE
PySocks dependency

### ISSUE THREAD

**Issue by jayvdb** [twilio/twilio-python#464]
On Python 3, the library depends on PySocks, however I do not see where it is used anymore, and the tests run ok without it, but maybe that is because of lots of mocking.

Apologies if I have missed something.

**Comment by Kerl1310** [comment]
Is this just a case of going through and double checking that the package is not being used then removing if so? If it is, then I'm more than happy to pick this up

**Comment by childish-sambino** [comment]
Yup, that’ll work.

**Comment by Kerl1310** [comment]
Can't seem to find any references to this package so I've opened a PR to remove
