### ISSUE TITLE
Make it possible to request "carrier" and "caller-name" types simultaneously in phone lookup fetch method

### ISSUE THREAD

**Issue by tstirrat15** [twilio/twilio-python#466]
**Version:** master

### Feature Request
The [type parameter](https://www.twilio.com/docs/lookup/api?code-sample=code-carrier-lookup-with-e164-formatted-number-5&code-language=Python&code-sdk-version=6.x#lookup-a-phone-number) on the API can accept both `carrier` and `caller-name` simultaneously by having both present in the GET parameters. This library doesn't support that yet.

**Comment by childish-sambino** [comment]
You can pass them in as a list. E.g.,
```
.fetch(
     type=['carrier', 'caller-name']
)
```

**Comment by tstirrat15** [comment]
Ah hmm... I didn't see that behavior when I was playing with my local copy of the library. Let me make sure I have the most recent version of the lib.

**Comment by tstirrat15** [comment]
My bad. I didn't have the most recent version of the lib. I appreciate the response.
