### ISSUE TITLE
KeyError: `queue_sid` when accessing `twilio.rest.api.v3010.account.queue.member.MemberInstance` 

### ISSUE THREAD

**Issue by ezwiefel** [twilio/twilio-python#469]
`queue_sid` is not in the payload for the call to `twilio.rest.api.v3010.account.queue.member.MemberInstance`

**Version: 6.28.0**

### Code Snippet
```python
queue = client.queues(queue_sid).fetch()
member = queue.members(call_sid).fetch()
```

### Exception/Log
```
Exception: KeyError: 'queue_sid'
  File "C:\Users\erikzwi\Projects\phone-patch-simplified\venv\lib\site-packages\twilio\rest\api\v2010\account\queue\member.py", line 247, in fetch
    call_sid=self._solution['call_sid'],
  File "C:\Users\erikzwi\Projects\phone-patch-simplified\venv\lib\site-packages\twilio\rest\api\v2010\account\queue\member.py", line 306, in __init__
    'queue_sid': payload['queue_sid'],
```

**Comment by ezwiefel** [comment]
The biggest concern to me here is that this was fixed previously and the Librarian reverted the change. This seems to be something I've seen create problems in a few places here.

**It really makes me hesitant to use this in production.**

**Comment by childish-sambino** [comment]
I _think_ this is the issue you're referring to about this change being reverted during code generation: https://github.com/twilio/twilio-python/issues/461

While they're similar, it's a different resource and was a bug in the backend.

In my testing I'm seeing `queue_sid` in the response.

Opening a [support ticket](https://support.twilio.com/) with the queue and call SIDs is the best route so the support team can debug those specific resources.
