### ISSUE TITLE
Twilio Insights is now Generally Available; Key Error on Fetching Insight Summary

### ISSUE THREAD

**Issue by tommyorndorff** [twilio/twilio-python#475]
I'm working to replace my non-SDK Insights calls over to using the helper libraries but it seems that after Insights was made GA during Signal 2019, the helper library hasnt been updated.  There are multiple references to the product still being in beta and I'm getting a result back which I assume is due to the class not matching the updated schema.

From the Insights schema doc that I have from 2019-07-19, there is this note in the change history for 2019-07-18: `Added direction to edge.properties`.  

**Version:**

```bash
$ /usr/local/opt/python/bin/python3.7 --version
Python 3.7.2
$ pip3 install --upgrade twilio
Requirement already up-to-date: twilio in /usr/local/lib/python3.7/site-packages (6.29.3)
<truncated>
```

### Code Snippet
```python
from twilio.rest import Client

# Your Account SID from twilio.com/console
account_sid = "<account_sid>"
# Your Auth Token from twilio.com/console
auth_token  = "<auth_token>"

client = Client(account_sid, auth_token)

result = client.insights.summary.get("<call_sid>")
insightInstance = result.fetch()

print(insightInstance)
```

### Exception/Log
```
$ /usr/local/opt/python/bin/python3.7 /Users/torndorff/Temp/insights.py
Traceback (most recent call last):
  File "/Users/torndorff/Temp/insights.py", line 11, in <module>
    insightInstance = insight1.fetch()
  File "/usr/local/lib/python3.7/site-packages/twilio/rest/insights/v1/summary.py", line 147, in fetch
    return CallSummaryInstance(self._version, payload, call_sid=self._solution['call_sid'], )
  File "/usr/local/lib/python3.7/site-packages/twilio/rest/insights/v1/summary.py", line 213, in __init__
    'direction': payload['direction'],
KeyError: 'direction'
```

### Steps to Reproduce
1.  Update credentials and call sid, run script

**Comment by childish-sambino** [comment]
This will be fixed in the next release, which is tomorrow.

**Comment by thinkingserious** [comment]
Release is live, thanks for your patience!

**Comment by tommyorndorff** [comment]
Cheers, thanks yall!  Confirmed working.
