### ISSUE TITLE
Breaking change with the message API and user blacklisting

### ISSUE THREAD

**Issue by slorg1** [twilio/twilio-python#478]
**Version:**

6.31.1 (latest)

### Code Snippet
```python

from twilio.rest import Client
from twilio.base.exceptions import TwilioRestException

try:
    msg = {
            "from_":"+YOUR_NUMBER_HERE",
            "to":"+YOUR_OTHER_NUMBER_HERE",
            "messaging_service_sid":TWILIO_MESSAGE_SERVICE_ID,
            "smart_encoded":True,
        }

    msg['body'] = "this is a test"
    res=Client(TWILIO_ACCOUNT_ID, TWILIO_AUTH_TOKEN).messages.create(**msg,)

    print(res.status, res.error_code, res.body,)

except TwilioRestException as e:

    if e.status == 400 and e.code == 21610:  # Twilio has black listed the user
        raise ValueError()

    raise
```

### Exception/Log
Exception: None, that's the problem

output:
```
accepted None this is a test
```

### Steps to Reproduce
1. using a phone number: send STOP to Twilio
2. using the code above send a message through Twilio
3. As of up-to a month ago, it would raise the `TwilioRestException` with the `21610` error code upon execution of the code for users who blacklisted the number/message service (said `STOP`).
4. instead, now it just "works" (no error, no status expressing the failure) and later in the Twilio logs I can see that the message was not sent.

This is an unadvertised breaking change... Is it on purpose? or a mistake?

**Comment by eshanholtz** [comment]
Hi @slorg1, we have been unable to recreate this issue. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact)

**Comment by slorg1** [comment]
Hi @eshanholtz ,

Thank you for your message. I am surprised by your answer: could you please post here what you got when you executed the code and your API and/or lib version so I can compare with mine?

Have you tested with [advanced opt-out on](https://www.twilio.com/blog/introducing-advanced-opt-out) ?

Thank you.

**Comment by eshanholtz** [comment]
Hi @slorg1,

My apologies for the curt wording. We were unable to reproduce the issue without additional details, like knowing that you were using advanced opt-out. After further investigation this appears to be expected behavior since copilot blacklist validation occurs asynchronously, meaning that messages sent to a blacklisted number fails further down the line than regular sms/mms messages. If you are new to using copilot, that could be why you're seeing this new "unexpected" behavior.

**Comment by slorg1** [comment]
Thank you! This was not transparent at all. You might want to update the doc :-)

**Comment by eshanholtz** [comment]
Thanks, I will pass along this feedback to the appropriate team to make this clearer in the messaging API docs.

For future readers who may have recently enabled copilot:
-  [messages sent from a message service will have an initial status of "accepted"](https://www.twilio.com/docs/sms/api/message-resource#appendix)
- [any delivery errors will be sent asynchronously to your StatusCallbackURL](https://www.twilio.com/docs/sms/services#send-a-message-with-copilot)
- [outgoing messages to users who have opted out will fail with error code 30004](https://www.twilio.com/docs/sms/services/advanced-opt-out#editing-opt-out-keywords-and-message)

**Comment by slorg1** [comment]
Hi, 

FYI, I have been getting the error code `21610` so far.

Thank you.
