### ISSUE TITLE
Not all needed packages are listed on requirements.txt

### ISSUE THREAD

**Issue by fefi95** [twilio/twilio-python#492]
Hi! I recently opened a small PR to fix and issue and when I tried to run the tests, discover that not all the packages are listed on `requirements.txt`. At least `pytz`  and `cryptography` are missing.

**Comment by childish-sambino** [comment]
I'm not seeing any issues when running and testing locally. I think the confusion comes from there being 2 requirements files: `requirements.txt` and `tests/requirements.txt`.  Could probably clean this up by having the `test` target depend on the `test-install` target.

But, anyway, does running this help with the original requirements file: `make test-install test`?

**Comment by fefi95** [comment]
I didn't see the `test/requirements.txt` file, running `make text-install test` does work!! (Probably this command could be documented on the contributing guidelines)

Sorry for the confusion and thanks!

**Comment by childish-sambino** [comment]
PR submitted for contributing guide update: #498
