### ISSUE TITLE
Cannot get room details of rooms with '/' in them.

### ISSUE THREAD

**Issue by Jaikishann** [twilio/twilio-python#503]
Hi team, When I create a room with room name such as `share/test` (which has '/' in it), I am not able to get room details using the https://www.twilio.com/docs/video/api/rooms-resource?code-sample=code-retrieve-an-in-progress-room-instance-by-uniquename&code-language=curl&code-sdk-version=json api. It works for the other room names.

**Version: 6.35.1**

### Code Snippet
Created the room using
```python
twilio_client.video.rooms.create(
  unique_name='share/test',
  type='group',
  media_region=nearest_server,
  record_participants_on_connect=false,
  status_callback=callback_url
)
```

And then trying to fetch room details
```python
twilio_client_object.video.rooms('share/test').fetch() # this returns null
```

The above can also be reproduced using postman.
### Postman request
```
HTTP GET to `https://video.twilio.com/v1/Rooms/share/test`
```

### Postman response
```
{
    "code": 20404,
    "message": "The requested resource /Rooms/testing/test was not found",
    "more_info": "https://www.twilio.com/docs/errors/20404",
    "status": 404
}
```

Is there any other api that I can use?

**Comment by childish-sambino** [comment]
Does it work when percent-encoded? `share%2Ftest`

**Comment by childish-sambino** [comment]
Percent-encoding didn't work when I tried it. Closing since this is not a change that can be made in the library, I've filed an internal ticket against the relevant product team (for reference: _VIDEO-2444_). I'll circle back here when I have an update.
