### ISSUE TITLE
unable to send whatsapp message with IP address as URL in body 

### ISSUE THREAD

**Issue by jshep321** [twilio/twilio-python#505]
### Issue Summary
I am unable to send a whatsapp message with a private IP URL (10.0.0.x).  My assumption is that the twilio api is enabling the preview_url in the whatsapp API (https://developers.facebook.com/docs/whatsapp/api/messages/text#urls) and failing since this is not a hostname, but an IP. Works perfectly fine (in both curl/bash and python) when I use a resolvable public URL (yummycupcakes.com as in the example or duckduckgo.com) OR a local hostname http://myserver.local/test.html.

I believe adding an option for no-preview-url might fix this.

### Steps to Reproduce
1. copy/update the example from here [https://www.twilio.com/console/sms/whatsapp/learn](url) with your sid/authtoken.
2. run to ensure success 
3. replace the default URL in body with a private IP address (I'm running apache2 on my 10.0.0.x network, so http://10.0.0.1/test.html)

### Code Snippet
See above URL

### Exception/Log
```
(Note this error code isn't in the docs...)
Error: 63030 Unsupported parameter for type of channels message
Description: Unsupported parameter for type of channels message
```
Also asked in stackoverflow.com: [https://stackoverflow.com/questions/59920079/custom-private-url-in-message-body-of-a-twilio-whatsapp-message](url)

### Technical details:
* twilio-python version: 6.35.3
* python version: 2.7.16

**Comment by xAlstrat** [comment]
I have the same problem. Glad I'm not the first one.
At least I know it will solve when I get a domain name. Thanks.

**Comment by childish-sambino** [comment]
Since this does not look to be an issue with the library itself, recommend [filing a support ticket](https://twilio.com/help/contact) for proper assistance.

**Comment by jshep321** [comment]
Thanks @childish-sambino. 

As a trial/non-paying customer (yet), I have no ability to file tickets yet.  If anyone else can submit a ticket for this, please do.
