### ISSUE TITLE
Random SSLErrors when calling the REST API

### ISSUE THREAD

**Issue by msaelices** [twilio/twilio-python#506]
### Issue Summary

Random errors like this:
```
SSLError: HTTPSConnectionPool(host='taskrouter.twilio.com', port=443): Max retries exceeded with url: /v1/Workspaces/WSXXXXXXXXXXXXXXXXXXXXXXXXXXX/Workers/WKXXXXXXXXXXXXXXXXXXXXXXXXXXX (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
```

I guess that is caused by small service outages, as the randomized nature of the issue.

A fix for that error would be retrying failed connections, using the `max_retries` param in the requests library (see [documentation](https://2.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter)).

**Comment by childish-sambino** [comment]
Feedback added.
