### ISSUE TITLE
`Message.price` not loaded from underlying json response in twilio-python

### ISSUE THREAD

**Issue by lukeburden** [twilio/twilio-python#511]
### Issue Summary
When using release 6.36.0 of this library with python 3.8.0, fetching a message does not seem to populate its `price` field.

### Steps to Reproduce
1. Setup a python 3.8.0 environment with version 6.36.0 of this library installed
2. Choose a SID you know exists, and try to fetch it using the code example in your documentation

### Fetching it using this library
```python
client = Client(<account-id>, <auth_token>)
message = client.messages('<message-SID').fetch()
message.price
None
```

### Now fetching it using `requests`:
```python
import requests
response = requests.get(
    'https://api.twilio.com/2010-04-01/Accounts/<account-id>/Messages/<message-SID>.json', 
    auth=HTTPBasicAuth("<account-id>", '<auth-token>')
)
response.json()['price']
'-0.00750'
```

### Technical details:
* twilio-python version: 6.36.0
* python version: 3.8.0

**Comment by lukeburden** [comment]
Hmm, I've had trouble reproducing this more recently. Once a message has a status of `delivered` is it fair to assume it should have `price` and `price_unit` populated?

**Comment by childish-sambino** [comment]
It's a matter of timing. More details on this issue: https://github.com/twilio/twilio-node/issues/45
