### ISSUE TITLE
Twilio 20503 Errors

### ISSUE THREAD

**Issue by jklaw90** [twilio/twilio-python#514]
The api seems to be a little unstable the last few days, I've been getting many service unavailable errors.  Is anything i can do about this, should i be retrying multiple times when this happens?

### Steps to Reproduce
1. Create room

### Code Snippet
```python
twilio_client.video.rooms.create(unique_name=id)
```

### Exception/Log
```
TwilioRestException(503, '/Rooms', 'Unable to create record: Service is unavailable. Please try again', 20503, 'POST')
```

### Technical details:
* twilio-python version: twilio==6.35.1
* python version: 3.7

**Comment by eshanholtz** [comment]
Hey @jklaw90,

This doesn't appear to be a library issue, and I wasn't able to recrate the 500's. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
