### ISSUE TITLE
Possible to log activity to console or some other log stream?

### ISSUE THREAD

**Issue by timstallmann** [twilio/twilio-python#516]
### Issue Summary
Apologies if this has come up before! I'm using twilio in combination with the [drfpasswordless](https://github.com/aaronn/django-rest-framework-passwordless) package to send login tokens; and for local testing and dev environments I'd really like to be able to see the messages as they go out while using Twilio's test API keys. 

Is there a way to flag the API to log outgoing requests to the console? Or maybe I'm missing some way to do that on my end further upstream? Also, are there any suggestions for unit tests including Twilio?

Thanks!

**Comment by thinkingserious** [comment]
Hello @timstallmann,

Outgoing requests are logged to the console ([debugger](https://www.twilio.com/docs/sms/debugging-tools#configure-custom-alerts)) on errors and alerts you specify. For non-error messages you may want to capture the request body right before you make the API call.

For mocking calls to Twilio, [`MagicMock`](https://docs.python.org/3.7/library/unittest.mock.html) may be worth looking into.

For further assistance not related to this helper library, please reach out to [Twilio Support](https://twilio.com/help/contact). Thanks!

With best regards,

Elmer
