### ISSUE TITLE
Image locally and collection of images

### ISSUE THREAD

**Issue by MaximKiselev** [twilio/twilio-python#518]
Hi, guys. How i can to attach image to message without any url (via file or bytearray).
Can i send collection of images in one message? (Does library supports multiple urls?)

**Comment by childish-sambino** [comment]
No, AFAIK you must provide a URL to attach an image. It is a list param so you can supply multiple URLs. Example here showing the list syntax: https://www.twilio.com/docs/sms/tutorials/how-to-send-sms-messages-python?code-sample=code-send-an-mms-message-with-an-image-url&code-language=Python&code-sdk-version=6.x

And some notes from the docs:
> The media can be of type gif, png, and jpeg and will be formatted correctly on the recipient's device. The media size limit is 5MB for supported file types (JPEG, PNG, GIF) and 500KB for other types of accepted media. To send more than one image in the message body, provide multiple media_url parameters in the POST request. You can include up to 10 media_url parameters per message. You can send images in an SMS message in only the US and Canada.

I've created an internal ticket asking about supporting images without needing a URL (reference ID: MSG-5659).

**Comment by MaximKiselev** [comment]
ok, thanks
