### ISSUE TITLE
Feature request: Change default hostname to allow local testing against mock endpoints

### ISSUE THREAD

**Issue by xgp** [twilio/twilio-python#521]
I looked for a way to change this in the existing library, and I can't find it.

I'd like to do some testing against my own mock endpoints, so I can validate the expected payloads without actually sending a message or requiring network connectivity. Is there a way to override the default hostname of `api.twilio.com`?

If not, it would be great to allow passing in a new hostname or base_url when creating a Client.

**Comment by Lewiscowles1986** [comment]
mock the session or client as shown in the tests in this repo. You don't want to be making real network calls in your test-suite

**Comment by xgp** [comment]
Thanks. 

Also, help@twilio suggested using a custom HTTP client that proxies the request to a different URL: https://www.twilio.com/docs/libraries/python/custom-http-clients-python. I suppose you could use this method if you had a reason to make real network calls.
