### ISSUE TITLE
Unable to update chat member last_consumption_timestamp

### ISSUE THREAD

**Issue by leibowitz** [twilio/twilio-python#526]
### last_consumption_timestamp not updating
Chat [members](https://www.twilio.com/docs/chat/rest/member-resource) have a `last_consumption_timestamp` property, which seems to be available as a parameter on the [create](https://github.com/twilio/twilio-python/blob/3907610762a67146e579423cca7896dd546647a4/twilio/rest/chat/v2/service/channel/member.py#L38) and [update](https://github.com/twilio/twilio-python/blob/3907610762a67146e579423cca7896dd546647a4/twilio/rest/chat/v2/service/channel/member.py#L302) methods. Though trying to update the value doesn't seem to have any effect.

### Steps to Reproduce
Create a channel, add a member, and update their last_consumption_timestamp via [member update](https://www.twilio.com/docs/chat/rest/member-resource#update-a-member-resource) method

### Code Snippet
```python
import datetime
import uuid
from twilio.rest import Client

ACCOUNT_ID = ''
AUTH_TOKEN = ''
SERVICE_SID = ''

client = Client(ACCOUNT_ID, AUTH_TOKEN)
chat_service = client.chat.services(SERVICE_SID)

user = chat_service.users.create(identity=str(uuid.uuid4()))

channel = chat_service.channels.create()

d1 = datetime.datetime(2016, 10, 30, 8, 10, 4)

member = chat_service.channels(channel.sid) \
                    .members \
                    .create(identity=user.identity, last_consumption_timestamp=d1)

print('Last Consumption:', member.last_consumption_timestamp)

d2 = datetime.datetime(2018, 10, 30, 8, 10, 4)
m2 = member.update(last_consumption_timestamp=d2)

print('Last Consumption:', m2.last_consumption_timestamp)

d3 = datetime.datetime(2019, 10, 30, 8, 10, 4)
m3 = chat_service.channels(channel.sid) \
                    .members(member.sid) \
                    .update(last_consumption_timestamp=d3)

print('Last Consumption:', m3.last_consumption_timestamp)

m = chat_service.channels(channel.sid) \
                    .members(member.identity) \
                    .fetch()
print('Last Consumption:', m.last_consumption_timestamp)
```

Output:
Last Consumption: 2016-10-30 08:10:04+00:00
Last Consumption: 2016-10-30 08:10:04+00:00
Last Consumption: 2016-10-30 08:10:04+00:00
Last Consumption: 2016-10-30 08:10:04+00:00

### Technical details:
* twilio-python version: 6.41.0
* python version: 3.7.4

**Comment by leibowitz** [comment]
Just adding more info, but it seems to work only when passing `last_consumed_message_index` as well in `update()`, even though that's not needed for create.

Any logical reasons for this?

**Comment by thinkingserious** [comment]
Hello @leibowitz,

`last_consumed_message_index` is used to determine what content a Member has consumed ([reference](https://www.twilio.com/docs/chat/consumption-horizon#message-read-status)). 

I'd like to get your feedback over to the appropriate team for further consideration. Could you please describe how you would expect or want the flow of API calls to work?

With best regards,

Elmer

**Comment by leibowitz** [comment]
Why would `last_consumed_message_index` be needed to update, when it's not needed to create member? I don't get it. Even if this is a requirement for the API, neither this library, nor the API is returning a failure when trying to update `last_consumption_timestamp` without also passing the `last_consumed_message_index`.

Surely, an error should be raised somewhere, rather than this silently failing scenario

**Comment by thinkingserious** [comment]
Thank you for the additional context! I am seeking assistance to help determine the best path forward.

**Comment by eshanholtz** [comment]
Hi @leibowitz 

I tested out your code and inspected the request and response payloads using `print(client.http_client.last_request)` and `print(client.http_client.last_response)`. It looks like the proper update data, with years `2018` and `2019` are being sent to the API, which indicates that this is an API level issue. This is not an issue that can be fixed in the library. I've filed a ticket with the relevant product team (reference ID: IPM-2354)

**Comment by leibowitz** [comment]
Hey @eshanholtz thanks for raising a ticket. As I mentioned in the previous [comment](https://github.com/twilio/twilio-python/issues/526#issuecomment-650190090), I would expect at least to receive an error. If the API doesn't allow to update for a good reason, then the validation should be done both in the client api and the server, in my view.

But I leave it to you guys to come up with the change that makes more sense to the overall API/library design.

**Comment by childish-sambino** [comment]
@leibowitz If it's not allowed in the update, then the product team will update their API definition to remove the param which will then trickle down to it being removed from this repo as well. If it's allowed but requires other params, then the backend should be updated to return the proper error when only the timestamp is provided. If it's allowed alone, then the backend should update to properly update the value. We'll see what they say and circle back when an update is available.
