### ISSUE TITLE
Python api not working when WhatsApp web is open

### ISSUE THREAD

**Issue by juanda2222** [twilio/twilio-python#529]
### Issue Summary
I have the Whatsapp beta integration of Twilio and when I open the Whatsapp web, the messages are not forwarded to the receiver.

### Steps to Reproduce
1. `pip install twilio`
2. Register number to the sandbox using the text message `join <sandbox-name>`
2. Oben Whatsapp web in Chrome (not sure if the web browser is the reason)
3. Send a message to Twilio's number: "+14155238886" using the code snippet (The message will remain in queue until the Whatsapp web tab is closed).

### Code Snippet
```python
# Download the helper library from https://www.twilio.com/docs/python/install
from twilio.rest import Client

# Your Account Sid and Auth Token from twilio.com/console
# DANGER! This is insecure. See http://twil.io/secure
account_sid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
auth_token = 'your_auth_token'
client = Client(account_sid, auth_token)

message = client.messages.create(
                              body='Hello there!',
                              from_='whatsapp:+14155238886',
                              to='whatsapp:+15005550006'
                          )

print(message.sid)
```

### Exception/Log
```
# No exception log.
```

### Technical details:
* twilio-python version: 6.43.0
* python 3.7.7
* Android 9 (Pie)
* Chrome version 83.0.4103.116

**Comment by eshanholtz** [comment]
This does not appear to be an issue with the twilio-python helper library. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
