### ISSUE TITLE
Inconsistent responses in PhoneNumber Pricing resource

### ISSUE THREAD

**Issue by lobsterick** [twilio/twilio-python#533]
### Issue Summary
When using Twilio Client, there is inconsistency between results in methods `list()` and `get()` for Phone Number Pricing Resource. 

From 215 records fetched via `list()`, only 71 was proper (having instance fetchable by `get()` with proper `instance.iso_country` field).

List of 144 codes without records:
`['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AN', 'AO', 'AS', 'AW', 'AX', 'AZ', 'BD', 'BF', 'BH', 'BI', 'BM', 'BN', 'BO', 'BS', 'BT', 'BY', 'BZ', 'CD', 'CF', 'CG', 'CI', 'CK', 'CM', 'CN', 'CR', 'CV', 'CX', 'DE', 'DJ', 'DM', 'EG', 'ES', 'ET', 'FJ', 'FK', 'FO', 'GA', 'GF', 'GI', 'GL', 'GM', 'GP', 'GQ', 'GT', 'GU', 'GW', 'GY', 'HN', 'HR', 'HT', 'IC', 'IE', 'IM', 'IN', 'IO', 'IQ', 'IT', 'JE', 'JO', 'KG', 'KH', 'KM', 'KN', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LY', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'MM', 'MN', 'MQ', 'MR', 'MS', 'MT', 'MV', 'MW', 'MZ', 'NC', 'NE', 'NG', 'NI', 'NO', 'NP', 'OM', 'PF', 'PG', 'PK', 'PS', 'PY', 'QA', 'RE', 'RU', 'RW', 'SA', 'SC', 'SD', 'SL', 'SM', 'SN', 'SO', 'SR', 'ST', 'SZ', 'TC', 'TG', 'TJ', 'TL', 'TM', 'TO', 'TR', 'TW', 'UA', 'UM', 'UY', 'UZ', 'VC', 'VE', 'VG', 'VI', 'WF', 'WS', 'XK', 'YE', 'ZM', 'ZW']`

### Steps to Reproduce

Using Python Twilio library with `Client`:

1. Fetch all pricing instances
2. Get all `iso_country` list from all instances
3. Iterate through `iso_country` list and - for every item - try get instance

### Code Snippet
```python
from twilio.rest import Client

account_sid = ''
account_token = ''

client = Client(account_sid, account_token)

# get all instances of Country Resource
all_countries_instances = client.pricing.phone_numbers.countries.list()

# fetch all codes from instances list
all_countries_iso_codes = [country.iso_country for country in all_countries_instances]

# iterate through all codes, trying to fetch single instance at once
# and check if it consist the same iso_code

with_code = []
without_code = []

for country_code in all_countries_iso_codes:
    single_instance = client.pricing.phone_numbers.countries.get(country_code).fetch()
    if single_instance.iso_country:
        with_code.append(country_code)
    else:
        without_code.append(country_code)

print("With code: ", with_code)
print("Without code: ", without_code)
```

### Exception/Log
```
With code:  ['AR', 'AT', 'AU', 'BA', 'BB', 'BE', 'BG', 'BJ', 'BR', 'BW', 'CA', 'CH', 'CL', 'CO', 'CY', 'CZ', 'DK', 'DO', 'DZ', 'EC', 'EE', 'FI', 'FR', 'GB', 'GD', 'GE', 'GH', 'GN', 'GR', 'HK', 'HU', 'ID', 'IL', 'IS', 'JM', 'JP', 'KE', 'KR', 'KY', 'LT', 'LU', 'LV', 'ML', 'MO', 'MU', 'MX', 'MY', 'NA', 'NL', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PR', 'PT', 'RO', 'RS', 'SE', 'SG', 'SI', 'SK', 'SV', 'TH', 'TN', 'TT', 'TZ', 'UG', 'US', 'VN', 'ZA']
Without code:  ['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AN', 'AO', 'AS', 'AW', 'AX', 'AZ', 'BD', 'BF', 'BH', 'BI', 'BM', 'BN', 'BO', 'BS', 'BT', 'BY', 'BZ', 'CD', 'CF', 'CG', 'CI', 'CK', 'CM', 'CN', 'CR', 'CV', 'CX', 'DE', 'DJ', 'DM', 'EG', 'ES', 'ET', 'FJ', 'FK', 'FO', 'GA', 'GF', 'GI', 'GL', 'GM', 'GP', 'GQ', 'GT', 'GU', 'GW', 'GY', 'HN', 'HR', 'HT', 'IC', 'IE', 'IM', 'IN', 'IO', 'IQ', 'IT', 'JE', 'JO', 'KG', 'KH', 'KM', 'KN', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LY', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'MM', 'MN', 'MQ', 'MR', 'MS', 'MT', 'MV', 'MW', 'MZ', 'NC', 'NE', 'NG', 'NI', 'NO', 'NP', 'OM', 'PF', 'PG', 'PK', 'PS', 'PY', 'QA', 'RE', 'RU', 'RW', 'SA', 'SC', 'SD', 'SL', 'SM', 'SN', 'SO', 'SR', 'ST', 'SZ', 'TC', 'TG', 'TJ', 'TL', 'TM', 'TO', 'TR', 'TW', 'UA', 'UM', 'UY', 'UZ', 'VC', 'VE', 'VG', 'VI', 'WF', 'WS', 'XK', 'YE', 'ZM', 'ZW']
```

### Technical details:
* twilio-python version: 6.44.00
* python version: 3.8

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team (reference ID _NUMBERS-8962_).
