### ISSUE TITLE
They just block your profile for no reason! I requested help and they just said I couldn't use their program. 

### ISSUE THREAD

**Issue by jfdecker** [twilio/twilio-python#534]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```python
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-python version:
* python version:

**Comment by childish-sambino** [comment]
Could you provide more details, code samples, and links for what you're trying to accomplish?
