### ISSUE TITLE
Help twilio voice call time limit

### ISSUE THREAD

**Issue by sadazs** [twilio/twilio-python#537]
Hi Twilio!
I need help
I buy 5-10 number and want use that list number random each call
and I want end call after 10-20s if user not get awnser

**Comment by eshanholtz** [comment]
Hi @sadazs 

According to the [documentation](https://www.twilio.com/docs/voice/api/call-resource#create-a-call-resource), you can pass in a `timeout` parameter, like so:

```python
# Download the helper library from https://www.twilio.com/docs/python/install
from twilio.rest import Client


# Your Account Sid and Auth Token from twilio.com/console
# DANGER! This is insecure. See http://twil.io/secure
account_sid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
auth_token = 'your_auth_token'
client = Client(account_sid, auth_token)

call = client.calls.create(
                        twiml='<Response><Say>Ahoy there!</Say></Response>',
                        to='+15558675310',
                        from_='+15552223214',
                        timeout=10
                    )

print(call.sid)
```

Note that:
> For some call flows, we will add a 5-second buffer to the timeout value you provide. For this reason, a timeout value of 10 seconds could result in an actual timeout closer to 15 seconds.

**Comment by sadazs** [comment]
Thank you
