### ISSUE TITLE
Region and edge parameters not supported for Video

### ISSUE THREAD

**Issue by DeTeam** [twilio/twilio-python#547]
### Issue Summary

When exploring `twilio-python` docs & source-code I found support for region and edge configuration. After trying to use it, got some exceptions (different for different regions, see below). 

* Are regions truly supported for all products?
* Is it possible to configure them per-product?

### Steps to Reproduce
1. Set `TWILIO_REGION=de1`
2. Try any method under `client.video`

### Exception/Log

For de1: 

```
ConnectionError: HTTPSConnectionPool(host='video.de1.twilio.com', port=443): Max retries exceeded with url: /v1/Rooms/... (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7fe6060af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

For ie1:

```
SSLError: HTTPSConnectionPool(host='video.ie1.twilio.com', port=443): Max retries exceeded with url: /v1/Rooms/... (Caused by SSLError(SSLCertVerificationError("hostname 'video.ie1.twilio.com' doesn't match either of 'console.ireland.ie1.twilio.com', 'console.ie1.twilio.com'")))
```

### Technical details:
* twilio-python version: 6.35.3
* python version: 3.8

**Comment by childish-sambino** [comment]
Region/edge expansion is underway. Best to check here for supported products: https://www.twilio.com/docs/global-infrastructure

**Comment by DeTeam** [comment]
Thanks, @childish-sambino. I'm looking forward to it 👍 

With the current implementation if multiple products are used at the same time from a single `rest.Client` using regions can lead to errors. Does it make sense to point this out in the docs already or better wait for the expansion to finish?

**Comment by childish-sambino** [comment]
I don't know if that needs to be called out explicitly here. Region is tied to auth so you'd need separate auth anyway if you're working across multiple regions.

**Comment by eshanholtz** [comment]
I'm closing this issue for now as we await edge/region expansion. Please open a new issue if the issue persists over time.
