### ISSUE TITLE
Changing room type on the fly

### ISSUE THREAD

**Issue by MarkoKostiv** [twilio/twilio-python#548]
**Question**
Is it possible to change the room type on the fly? 

We are developing a use case when users can start a 1:1 video call and add other participants on-demand. Therefore we aim to start this call in a `peer-to-peer` manner and changing it to `group` once users invite new participants.

Does the current video API support this type of behavior?

Thanks

**Comment by eshanholtz** [comment]
No, a room type may only be specified upon room creation.
