### ISSUE TITLE
Time-based bug in the Deactivations API

### ISSUE THREAD

**Issue by jmtroth0** [twilio/twilio-python#549]
### Issue Summary
I set up a cron to pull the [US deactivations](https://www.twilio.com/docs/sms/deactivated-phone-numbers) everyday for the previous day at 3am UTC and received the error response pasted below. This happened every day for about about a week, while it always worked when I tested it during the workday.

I then adjusted the cron to run at 12pm UTC instead, and the request succeeds.

### Code Snippet
```python
yesterday = arrow.utcnow().shift(days=-1).date()
twilio_client.messaging.deactivations().fetch(date=yesterday)
```

### Exception/Log
```
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to fetch record: Specified date is unavailable. Historical data is only available from 09/05/2020 onwards.
```

### Technical details:
* twilio-python version:  `twilio==6.47.0`
* python version: 3.7.8

**Comment by thinkingserious** [comment]
Hello @jmtroth0,

It looks like you may have set the time before the publication of the latest deactivations. Is there a particular need to use 3am UTC? (i.e. what is the issue with using 12pm UTC?)

With best regards,

Elmer
