### ISSUE TITLE
Weird behavior with record verb

### ISSUE THREAD

**Issue by navdeepghai1** [twilio/twilio-python#550]
The call is not disconnecting even after the hangup dial after the recording and It keeps calling the same webhook(voice_call) again and again which is leading the recording multiple recording.

I am sending this instruction when Twilio calls the incoming call webhook(voice_call)

Attaching the screenshot for your ref
<img width="2306" alt="Screen Shot 2020-12-18 at 9 30 35 PM" src="https://user-images.githubusercontent.com/30634335/102678926-9618fb80-4179-11eb-97d3-6f0297a4e2cf.png">

**Comment by alankleindev** [comment]
Record Verb needs action URL or will loop
https://www.twilio.com/docs/voice/twiml/record#attributes-action

> After making this request, Twilio will continue the current call using the TwiML received in your response. Keep in mind that by default Twilio will re-request the current document’s URL. This can lead to unwanted looping behavior if you’re not careful. Any TwiML verbs occurring after a <Record> are unreachable.

**Comment by navdeepghai1** [comment]
@alankleindev  thanks for providing such info. will close the ticket after the verification.

**Comment by eshanholtz** [comment]
@navdeepghai1 Were you able to implement fix the looping behavior you were seeing?

**Comment by navdeepghai1** [comment]
@eshanholtz Yes! it's working as  suggested and expected
