### ISSUE TITLE
requirements not locked....

### ISSUE THREAD

**Issue by jklaw90** [twilio/twilio-python#551]
the jwt lib updated to 2.0 with breaking changes.

the requirements.txt doesn't lock down any dependency...

**Comment by lidia-saf** [comment]
We face the same issue. I see that the pull request to pin the pyjwt dependency is merged yesterday. Are there any plans to release a new version of twilio-python with that pull request?

**Comment by JenniferMah** [comment]
Hi @lidia-saf the new version of twilio-python will be released 1/13/21.

**Comment by jklaw90** [comment]
https://pip.pypa.io/en/stable/user_guide/#requirements-files

@thinkingserious it probably would make sense to lock all the requirements down, and you can specify **less than** the next major release if you guys don't want to explicitly lock down the version. not sure why you wouldn't want to though

**Comment by karls** [comment]
Just to notify people in this thread, I opened a PR #560 to upgrade PyJWT to 2.x and with it drop support for Python 2.7 and 3.0-3.5.
