### ISSUE TITLE
Drop Python <= 3.5 support

### ISSUE THREAD

**Issue by thinkingserious** [twilio/twilio-python#557]
It is on our backlog to drop support for Python <= 3.5 as they are EOL. This issue exists to help identify potential issues an to gather general feedback. Please feel free to comment with any questions or concerns.

Related Issue: https://github.com/twilio/twilio-python/issues/556

**Comment by wavenator** [comment]
I am totally in favor of this movement. There are so many reasons to make that move, and I think the strongest one is being aligned with the community. Every day more and more packages drop their Python2 support.

**Comment by hugorodgerbrown** [comment]
Coming here from the #556 issue - having to support 2/3 and pinning to an old PyJWT is causing us upgrade isses.

**Comment by ryanhiebert** [comment]
In favor as well. Looking to update PyJWT as well, and I think that dropping Python 2 is perfectly reasonable. If folks need to stay on Python 2 for a bit longer, the old versions of this library don't go away, so I don't think we need to worry about that, really.

**Comment by childish-sambino** [comment]
Updated title and description. We will be looking to major version roll this library in the coming weeks and drop support for Python <= 3.5 and migrate to PyJWT 2. Comms will go out to customers using such versions of Python and a recent release of this library to notify them of the breaking change should they choose to upgrade.

**Comment by shwetha-manvinkurke** [comment]
Closed in #560
