### ISSUE TITLE
pylint not callable warning

### ISSUE THREAD

**Issue by dwbelliston** [twilio/twilio-python#559]
### Issue Summary
Hey - wondering if i could get some help on this. Pylint is not happy with the way im calling the client.

### Code Snippet
```python
from twilio.rest import Client

TWILIO_ACCOUNT_SID_SECRET_NAME: str = environ.get("TWILIO_ACCOUNT_SID_SECRET_NAME", "")
TWILIO_AUTH_TOKEN_SECRET_NAME: str = environ.get("TWILIO_AUTH_TOKEN_SECRET_NAME", "")


account_sid = ssm.get_secret(TWILIO_ACCOUNT_SID_SECRET_NAME)
auth_token = ssm.get_secret(TWILIO_AUTH_TOKEN_SECRET_NAME)

cli_twilio = Client(account_sid, auth_token)

# ...
local = cli_twilio.available_phone_numbers("US").local.list(
    area_code=area_code, limit=limit, sms_enabled=sms_enabled
)

```

![image](https://user-images.githubusercontent.com/11450118/106908869-eeba3e80-66bc-11eb-9d97-395f9d50c49c.png)

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-python version: `twilio = "^6.51.1"`
* python version: `3.8`

**Comment by eshanholtz** [comment]
Looks like this is a [known pylint issue](https://github.com/PyCQA/pylint/issues/1730). The code should still execute, regardless.

**Comment by dwbelliston** [comment]
right on - ill just disable it and move on :) - thanks for confirming
