### ISSUE TITLE
Campaign status missing from UsAppToPersonInstance

### ISSUE THREAD

**Issue by brocksamson** [twilio/twilio-python#564]
### Issue Summary
The UsAppToPersonInstance exposes a status property that is always None.  This is because https://messaging.twilio.com/v1/Services/MGXXXXXXXXX/Compliance/Usa2p does not contain a property named status.  I believe that this is supposed to be mapped to the campaign_status property that does exist in the Usa2p response.

### Steps to Reproduce
1. Fetch a messaging status by id.
2. fetch the associated us_app_to_person.
3. Result is an object that has a status of None, and there is no way to ask the object for the current campaign status.

### Code Snippet
```
client = Client(sid, secret)
service = client.messaging.services('MGXXXXXXXXXX').fetch()
a_to_p = = service.us_app_to_person.fetch()
print(a_to_p.status)  # always None.
print(a_to_p.__dict__)  # campaign status is nowhere to be found in the properties on the object.
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-python version: 6.57.0
* python version: ANY (I used 3.6 & 3.8)

**Comment by JenniferMah** [comment]
Hi @brocksamson it looks like `status` was recently renamed to `campaign_status` in [v6.58.0](https://github.com/twilio/twilio-python/releases/tag/6.58.0). Can you upgrade your version of twilio-python to version v6.58.0 and test using `campaign_status` agian?

**Comment by brocksamson** [comment]
@JenniferMah I've confirmed that campaign_status is working in v6.58.0.  Closed.
