### ISSUE TITLE
what am i doing wrong

### ISSUE THREAD

**Issue by antonio-irarrazaval** [twilio/twilio-python#573]
### what am i doing wrong or a Issue ?
In Studio Flow, I use a  **HTTP request widget** to send same information to main Django app and return another information. 
It's works... and exchange the Json information well.
BUT:  In twilio.request_validator.Validator.validate always get INVALID! from HTTP request,I have tried to perform different combinations, but without success !!! .  Obviously it could be a potentially unsafe issue.
I try many-many times  [this tutorial](https://www.twilio.com/docs/usage/tutorials/how-to-secure-your-django-project-by-validating-incoming-twilio-requests) without success

### Environment
1. Environment: Django 3.2, Python 3.8, rest_api, twilio, 

Twilio flow:

![image](https://user-images.githubusercontent.com/49562616/129203896-16707338-212b-4364-b330-062673637e55.png)

### Django Class View exposed
```python
@method_decorator(csrf_exempt, name='dispatch')
class TestAuth(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body.decode("utf-8"))
        uri = request.build_absolute_uri()
        TW_signature = request.META.get('HTTP_X_TWILIO_SIGNATURE', '')
        TW_token = '5177461b85e2881eaf4bd8108c9XXXXX'
        LOG.info(f" TestAuth: \n data incomming {data}, \n uri: {uri}\n Signature: {TW_signature} \n auth_token:{TW_token}")
        validator = RequestValidator(TW_token)
        is_valid = validator.validate(uri, params=data, signature=TW_signature)
        LOG.info(f" VALIDADOT IS: {is_valid}")
        context = {
            'var1': 1,
            'var2': 2
        }
        return JsonResponse(data=context)
```

### Exception/Log
```
[12/Aug/2021 08:59:40] "GET / HTTP/1.1" 404 179
 INFO     [views.py:40]  TestAuth: 
 data incomming {'var_name1': 'value1', 'var_name2': 'value2'}, 
 uri: https://c6a8ffb592e7.ngrok.io/tw/testsecure/?bodySHA256=14ef646a827ca02db13bf7bd4b7bf0cd2f234e7d5a2a6e9a6fcbb6dd76b43d8c
 Signature: DSabcebrSRlTPpl+e0G497wkWik= 
 auth_token:5177461b85e2881eaf4bd81XXXXX
 INFO     [views.py:44]  VALIDADOT IS: False
[12/Aug/2021 09:01:40] "POST /tw/testsecure/?bodySHA256=14ef646a827ca02db13bf7bd4b7bf0cd2f234e7d5a2a6e9a6fcbb6dd76b43d8c HTTP/1.1" 200 22

```

### Debug:

Debugging the code, it is curious that "request.POST" is empty and "request.body" has a binary value that has a value on the json in hard-coded text...  this can be fixed with "data = json.loads(request.body.decode("utf-8"))", but that is not the natural option to solve

![image](https://user-images.githubusercontent.com/49562616/129206627-82b6e557-aa1d-4b42-8449-4cba51924ba0.png)

### Issue for Django?

With another client, in which he occupied "Flask", there was no problem and it worked perfectly.
I try many-many times  [this tutorial](https://www.twilio.com/docs/usage/tutorials/how-to-secure-your-django-project-by-validating-incoming-twilio-requests) without success

Thank in advice.

**Comment by JenniferMah** [comment]
Hi @antonio-irarrazaval 
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
