### ISSUE TITLE
Is this library thread-safe?

### ISSUE THREAD

**Issue by wojcikstefan** [twilio/twilio-python#580]
I haven't seen anything in your documentation, code, nor old GH issues that would explicitly say whether this library is or isn't thread-safe (and whether that's even the goal). I think it would be good to address that, especially since sending multiple concurrent requests to Twilio's API is a pretty common use case. A similar question has already been asked & answered for your Java client (https://github.com/twilio/twilio-java/issues/441).

Based on my own (admittedly shallow) investigation, using your Python client **may not be thread-safe**  because:
1. By default, [`TwilioHttpClient` uses `requests.Session`](https://github.com/twilio/twilio-python/blob/4ac3fd5465e9e826db0c98b3e2b1dd1134d7cc88/twilio/http/http_client.py#L31) and [there's still an open issue](https://github.com/psf/requests/issues/2766) discussing whether that is thread-safe or not.
2. Using [`TwilioHttpClient.last_request`](https://github.com/twilio/twilio-python/blob/4ac3fd5465e9e826db0c98b3e2b1dd1134d7cc88/twilio/http/http_client.py#L34)/[`last_response`](https://github.com/twilio/twilio-python/blob/4ac3fd5465e9e826db0c98b3e2b1dd1134d7cc88/twilio/http/http_client.py#L35) is definitely not thread-safe.

**Comment by childish-sambino** [comment]
Your analysis is correct. Until the thread-safety of `requests.Session` can be proven then the thread-safety of the client here cannot made. For `last_request/response`, these are intended for testing purposes only and should not be relied upon in a production set up.

**Comment by beebzz** [comment]
Thanks for the documentation suggestion @wojcikstefan! It's been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
