### ISSUE TITLE
assertDictContainsSubset was removed in Python 3.11

### ISSUE THREAD

**Issue by tirkarthi** [twilio/twilio-python#584]
### Issue Summary

The deprecated unittest aliases were removed in python/cpython#28268 in Python 3.11

### Steps to Reproduce

```
twilio-python/tests/unit/jwt/test_jwt.py:        self.assertDictContainsSubset({
twilio-python/tests/unit/jwt/test_client_validation.py:        self.assertDictContainsSubset({
twilio-python/tests/unit/jwt/test_client_validation.py:        self.assertDictContainsSubset({
```

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized (Reference ID: DI-1915). Pull requests and +1s on the issue summary will help it move up the backlog.
