### ISSUE TITLE
Relax tests requirements

### ISSUE THREAD

**Issue by rominf** [twilio/twilio-python#595]
### Issue Summary
I'm a Fedora packager for `python3-twilio`. I get an error during build process related with too strict version pinning for `mock` and `sphinx`. I don't think this is necessary: I've made a patch which removes pinning, and hence `mock 4.0.3` and `Sphinx 4.4.0` are installed. And the tests pass. Consider removing the pinning, or at least, make it use `>=` operator. It'll make lives of packagers easier.

### Exception/Log
```
...
No matching package to install: 'python3dist(mock) = 0.8'
Package python3-packaging-21.3-2.fc36.noarch is already installed.
Package python3-pip-22.0.4-1.fc37.noarch is already installed.
Package python3-setuptools-60.9.3-1.fc37.noarch is already installed.
No matching package to install: 'python3dist(sphinx) = 1.8'
...
```

### Technical details:
* twilio-python version: 7.8.0
* python version: 3.10

**Comment by paulwouters** [comment]
+1
