### ISSUE TITLE
No message body in post-event Webhook, Conversations API

### ISSUE THREAD

**Issue by AleksaPetrovicRBT** [twilio/twilio-python#603]
### Issue Summary
When sending message with media through REST API, on post-event webhook `body` parameter in request is not present. Since my location is not USA or Canada, I can not confirm it's same issue when sending MMS from phone.

### Steps to Reproduce
1. Upload media, through wrapped request to twilio (since https://github.com/twilio/twilio-python/issues/596 is not resolved yet)
2. Create message, attach media sid

### Code Snippet
```python
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-python version: 7.8.1
* python version: 3.9

**Comment by AleksaPetrovicRBT** [comment]
https://www.twilio.com/docs/conversations/conversations-webhooks#onmessageadded relevant documentation.

**Comment by childish-sambino** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
