### ISSUE TITLE
API returning duplicate CDR

### ISSUE THREAD

**Issue by orcawave-dliu** [twilio/twilio-python#606]
### Issue Summary
The API is returning duplicate records.

### Steps to Reproduce
1. Call the API to get CDR
2. Look for duplicate the SID in the dataset returned from the API.

### Code Snippet
```python
calls = client.calls.list(end_time_after=datetime(dt.year, dt.month, dt.day, dt.hour, 0, 0),end_time_before=datetime(dt.year, dt.month, dt.day, dt.hour, 59, 59), status='completed')
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-python version: 7.8.2
* python version: 3.9 / 3.10

**Comment by orcawave-dliu** [comment]
Hi Jennifer

An hour worth of CDR has total of 128900 records. 18289 were duplicate with the same SID. I did try with the latest version v7.9.1 of twilio-python. Same result.

**Comment by beebzz** [comment]
Hi @orcawave-dliu, since this seems like an API issue, feel free to file a [support ticket](https://twilio.com/help/contact) in order to properly debug this issue.

**Comment by orcawave-dliu** [comment]
There was a ticket already open with the support team. They told me submit the issue on github.

Thanks!

David Liu
Senior Database Developer
Orcawave
