### ISSUE TITLE
Are there plans for Content API integration?

### ISSUE THREAD

**Issue by adamhoffstein** [twilio/twilio-python#619]
### Issue Summary
Not a bug, but I have been working on a wrapper for creating, submitting content for approval and sending content with the new Content API from Twilio. I was wondering if any official client is currently in the works or if this is something I could help contribute.

**Comment by rakatyal** [comment]
Hi @adamhoffstein, this is on our radar but not likely to arrive in the short term since this will be built on top of other features  being worked on currently in the SDK. Pull requests and +1s will help it move up the backlog.

**Comment by tiwarishubham635** [comment]
Hi @adamhoffstein! You can check the new content APIs [here](https://github.com/twilio/twilio-python/tree/main/twilio/rest/content/v1)

**Comment by jameschristopher** [comment]
@tiwarishubham635 can you give an example of how to use the Content API with the SDK? There is no documentation on the Twilio docs site. A simple example like the one here: https://www.twilio.com/docs/content/twilio-text would be great. I've tried an implementation myself and am just getting lost in different errors.
