### ISSUE TITLE
UTF-8 content doesn't get properly serialized

### ISSUE THREAD

**Issue by igz-gp** [twilio/twilio-python#623]
### Issue Summary
UTF-8 content doesn't get properly serialized

### Steps to Reproduce
1. Add any utf-8 content to a `VoiceResponse`. E.g. `voice_response = VoiceResponse(); voice_response.say("An utf-8 character: ñ")`
2. Serialize the voice_response. E.g. `str(voice_response)`
3. The result is `'<?xml version="1.0" encoding="UTF-8"?><Response><Say>An utf-8 character: &#241;</Say></Response>'`. The `ñ` character was html encoded.

### Technical details:
* twilio-python version: 7.15.0
* python version: 3.9.15

### Proposed solution:
Replace `xml = ET.tostring(self.xml()).decode('utf-8')`
with `xml = ET.tostring(self.xml(), encoding='utf-8').decode('utf-8')`
in https://github.com/twilio/twilio-python/blob/15eb9be126f562c80175d478fd3eafb5d1cc7efb/twilio/twiml/__init__.py#L67

**Comment by igz-gp** [comment]
I could make a PR if you want me to :)

**Comment by JenniferMah** [comment]
Hi @igz-gp! Thanks for opening an issue! Please feel free to open a PR with a fix and our team will add it to our review backlog.
