### ISSUE TITLE
Could not install packaged due to an OSError 

### ISSUE THREAD

**Issue by mattsegura** [twilio/twilio-python#625]
Currently unable to install all of the packages, here's there error I'm getting. I have pip to the latest version and I'm running python 3.10 on windows 11. 

![image](https://user-images.githubusercontent.com/61678138/202361693-ec5a9706-3942-400e-b843-262f75b791d1.png)

**Comment by mattcole19** [comment]
A similar [issue](https://github.com/twilio/twilio-python/issues/535) has been brought up before and was resolved. See if their solution applies to you as well!
