### ISSUE TITLE
TwilioHttpClient's timeout type hint is incorrect

### ISSUE THREAD

**Issue by byarmis** [twilio/twilio-python#630]
### Issue Summary
The type hint in `twilio-python/http_client.py` 's [line 25](https://github.com/twilio/twilio-python/blob/main/twilio/http/http_client.py#L25) is incorrect.  Currently, it's an `int`, but it's passed more-or-less directly to `requests.sessions.send` which accepts [a float](https://github.com/psf/requests/blob/main/requests/sessions.py#L538)

### Steps to Reproduce
1. Import `TwilioHttpClient`
2. Specify timeout with a float
3. Type check (with IDE)
4. Get error

### Code Snippet
```python
http_client = TwilioHttpClient(timeout=3.1)
```

### Exception/Log
```
Expected type 'int', got 'float' instead
```
![image](https://user-images.githubusercontent.com/1594170/207099922-8333ae5a-f888-4234-a012-c44ef050aaeb.png)

### Technical details:
* twilio-python version: `twilio-7.15.4`
* python version: 3.10

Mypy does not validate typing in docstrings, but my IDE (PyCharm) at least does

**Comment by childish-sambino** [comment]
Makes sense will. Take a loot at the PR.

Note that the request interface types this as `float`: https://github.com/twilio/twilio-python/blob/85706b3942a0da8831c6653ec1af1278b066a958/twilio/http/http_client.py#L55
