### ISSUE TITLE
tollfree_verification.py is gone from messaging/v1

### ISSUE THREAD

**Issue by Kotzyk** [twilio/twilio-python#712]
### Issue Summary
messaging.v1.tollfree_verification is missing from versions 8.2.0 onwards with no mention in the Changelog. Last version it was present (and had changes to as well) was[ 8.1.0](https://github.com/twilio/twilio-python/blob/8.1.0/twilio/rest/messaging/v1/tollfree_verification.py)

That's pretty much it, a file disappeared from the messaging.v1 module without any mentions about it so it doesn't look intentional

**Comment by AsabuHere** [comment]
Hi @Kotzyk , Thank you for the heads up! We are looking into this issue

**Comment by AsabuHere** [comment]
Hi @Kotzyk, tollfree_verification.py is present in latest version of twilio-python library. Link : https://github.com/twilio/twilio-python/blob/main/twilio/rest/messaging/v1/tollfree_verification.py
