### ISSUE TITLE
WARNING: Connection pool is full

### ISSUE THREAD

**Issue by lightiverson** [twilio/twilio-python#714]
### Issue Summary
We're using the twilio-python library to send out thousands of SMS messages concurrently using Python's concurrent features library. During usage the Logging module gives us a warning saying: `urllib3.connectionpool:_put_conn:304 - Connection pool is full, discarding connection: api.twilio.com`.

### Steps to Reproduce
1. Get an array of valid phonenumbers
2. Map the client.message.create function using concurrent.futures
3. Run the program with Logging

### Code Snippet
```python
def send_session_message():
      message = client.messages.create(
          body=body,
          from_=from_,
          to=[recipient],
          persistent_action=coordinates,
      )

with concurrent.futures.ThreadPoolExecutor() as executor:
      results = executor.map(
          send_session_message,
          recipients,
          repeat(body),
          repeat(from_),
          repeat(messaging_service_sid),
      )
```

### Exception/Log
```
# WARNING  | urllib3.connectionpool:_put_conn:304 - Connection pool is full, discarding connection: api.twilio.com
```

### Technical details:
* twilio-python version:  7.1.0
* python version: 3.8.12

**Comment by charan678** [comment]
hello @lightiverson The issue is with your implementation of connection pool logic nothing to do with twilio-python. you can try blocking new connection when connection pool is full. you can look into python/urllib documentation and find the solution to handle connection pool full issue. This [link](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#customizing-pool-behavior) might be helpful to you.

**Comment by lightiverson** [comment]
hi @charan678 thanks for the link! We came across this information and handled the connection pool full issue in the TwilioHttpClient like so:

<img width="753" alt="afbeelding" src="https://github.com/twilio/twilio-python/assets/33266555/1bda5016-6487-4c79-9b99-aae224641ef6">

This seems to have solved the problem. However, you mentioned that the issue is has nothing to do with twilio-python. Is there a better solution which does not involve editing the twilio-python package?

**Comment by lightiverson** [comment]
@charan678 as for the package version, you're right we will update to the latest version asap. Thank you.

**Comment by charan678** [comment]
@lightiverson We can't remove this snippet, It limits maximum pool size. you can set max_worker parameter in concurrent.futures.ThreadPoolExecutor.

**Comment by lightiverson** [comment]
@charan678 it seems there's a misunderstanding. The highlighted snippet, is what we have added locally to the twilio-python source code to solve this issue. It currently does not exist in your repository.

Would you like us to make a pull request to have this snippet added?

**Comment by lightiverson** [comment]
@charan678 No worries! Got it, we'll raise the pull request shortly, with the max_workers set to equal or less than 10. Thanks for your help.
