### ISSUE TITLE
Drop unnecessary dependency on `pytz` - stdlib provides `datetime.timezone.utc`

### ISSUE THREAD

**Issue by Zac-HD** [twilio/twilio-python#720]
This package currently depends on `pytz`, which [is incompatible with Python's standard timezone handling](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html) and thus being removed throughout the ecosystem in favor of the `zoneinfo` module.  When I saw that `twilio` was using it, my heart sank but I resolved to open an issue.

But there's good news: _you're not actually using any pytz interfaces!_  Literally the only thing you're using is the `pytz.utc` timezone object, which can be perfectly replaced with the [standard library `datetime.timezone.utc`](https://docs.python.org/3/library/datetime.html#datetime.timezone.utc) object in [all four places it's used](https://github.com/search?q=repo%3Atwilio%2Ftwilio-python%20pytz&type=code) (including tests).  Doing so should make your and, all your users', dependency-management ever so slightly easier.

I'll send a PR shortly, if nobody beats me to the punch 🙂

**Comment by AsabuHere** [comment]
Hi @Zac-HD, This PR is reviewed and approved by our team. Please merge once the checks are successful
