### ISSUE TITLE
Imported library does not exist

### ISSUE THREAD

**Issue by geospith** [twilio/twilio-python#772]
The path twilio.rest.preview.understand.assistant does not exist, therefore this import breaks at runtime:

from twilio.rest.preview.understand.assistant import AssistantList

https://github.com/twilio/twilio-python/blob/7b52a49026a45bad6cb4e2840cb8f77d51a216f8/twilio/rest/preview/__init__.py#L12

**Comment by tiwarishubham635** [comment]
Let's club this under #773 as they are the same issue. Will be looking at it
