### ISSUE TITLE
Python Versions Support

### ISSUE THREAD

**Issue by jack-tutor** [twilio/twilio-python#802]
### Issue Summary

Hello - I'm trying to understand what versions of python this package supports.  Specifically, I am interested in:
* if python 3.12 is supported
* if not, are there plans and/or a timeline to support it

The README says that it is not supported: https://github.com/twilio/twilio-python?tab=readme-ov-file#supported-python-versions but this PR extended testing to support it: https://github.com/twilio/twilio-python/pull/741/files and it doesn't seem to be forbidden in `setup.py`: https://github.com/twilio/twilio-python/blob/main/setup.py#L22.  I don't seem to run into issues installing it into a 3.12 python project - though I have not tried to actually make use of it.  Is this a "use-at-your-own-risk" sort of situation, where correct behavior isn't promised for 3.12.

Thank you for your time.

**Comment by manisha1997** [comment]
Python v3.12 is supported. We will update the readme.
