### ISSUE TITLE
Resource objects should support json.dumps

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-python#88]
Or, some kind of object.to_json() method which would give you the original JSON. Right now trying to make a server-side API request and just pass through the JSON response is difficult, without resorting to Requests or similar.

It would also be nice if printing a message returned its JSON representation. Right now you get

``` python
>>>> msg = client.sms.messages.get('SM123')
>>>> msg
<twilio.rest.resources.SmsMessage at 0x101fa6a90>
```

Which doesn't tell you much at a glance.

**Comment by rns4731** [comment]
@kevinburke This is supported now using `_properties`, so you can try `msg._properties`.
